/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.2-Docker-4.0.0 (4.5)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// checks if the SubnetPurposeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubnetPurposeRequest{}

// SubnetPurposeRequest Adds support for custom fields and tags.
type SubnetPurposeRequest struct {
	Name                 string             `json:"name"`
	Slug                 string             `json:"slug" validate:"regexp=^[-a-zA-Z0-9_]+$"`
	Color                *string            `json:"color,omitempty" validate:"regexp=^[0-9a-f]{6}$"`
	CustomFieldData      interface{}        `json:"custom_field_data,omitempty"`
	Tags                 []NestedTagRequest `json:"tags,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SubnetPurposeRequest SubnetPurposeRequest

// NewSubnetPurposeRequest instantiates a new SubnetPurposeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubnetPurposeRequest(name string, slug string) *SubnetPurposeRequest {
	this := SubnetPurposeRequest{}
	this.Name = name
	this.Slug = slug
	return &this
}

// NewSubnetPurposeRequestWithDefaults instantiates a new SubnetPurposeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubnetPurposeRequestWithDefaults() *SubnetPurposeRequest {
	this := SubnetPurposeRequest{}
	return &this
}

// GetName returns the Name field value
func (o *SubnetPurposeRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SubnetPurposeRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SubnetPurposeRequest) SetName(v string) {
	o.Name = v
}

// GetSlug returns the Slug field value
func (o *SubnetPurposeRequest) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *SubnetPurposeRequest) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *SubnetPurposeRequest) SetSlug(v string) {
	o.Slug = v
}

// GetColor returns the Color field value if set, zero value otherwise.
func (o *SubnetPurposeRequest) GetColor() string {
	if o == nil || IsNil(o.Color) {
		var ret string
		return ret
	}
	return *o.Color
}

// GetColorOk returns a tuple with the Color field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubnetPurposeRequest) GetColorOk() (*string, bool) {
	if o == nil || IsNil(o.Color) {
		return nil, false
	}
	return o.Color, true
}

// HasColor returns a boolean if a field has been set.
func (o *SubnetPurposeRequest) HasColor() bool {
	if o != nil && !IsNil(o.Color) {
		return true
	}

	return false
}

// SetColor gets a reference to the given string and assigns it to the Color field.
func (o *SubnetPurposeRequest) SetColor(v string) {
	o.Color = &v
}

// GetCustomFieldData returns the CustomFieldData field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SubnetPurposeRequest) GetCustomFieldData() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.CustomFieldData
}

// GetCustomFieldDataOk returns a tuple with the CustomFieldData field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SubnetPurposeRequest) GetCustomFieldDataOk() (*interface{}, bool) {
	if o == nil || IsNil(o.CustomFieldData) {
		return nil, false
	}
	return &o.CustomFieldData, true
}

// HasCustomFieldData returns a boolean if a field has been set.
func (o *SubnetPurposeRequest) HasCustomFieldData() bool {
	if o != nil && !IsNil(o.CustomFieldData) {
		return true
	}

	return false
}

// SetCustomFieldData gets a reference to the given interface{} and assigns it to the CustomFieldData field.
func (o *SubnetPurposeRequest) SetCustomFieldData(v interface{}) {
	o.CustomFieldData = v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *SubnetPurposeRequest) GetTags() []NestedTagRequest {
	if o == nil || IsNil(o.Tags) {
		var ret []NestedTagRequest
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubnetPurposeRequest) GetTagsOk() ([]NestedTagRequest, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *SubnetPurposeRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []NestedTagRequest and assigns it to the Tags field.
func (o *SubnetPurposeRequest) SetTags(v []NestedTagRequest) {
	o.Tags = v
}

func (o SubnetPurposeRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubnetPurposeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["slug"] = o.Slug
	if !IsNil(o.Color) {
		toSerialize["color"] = o.Color
	}
	if o.CustomFieldData != nil {
		toSerialize["custom_field_data"] = o.CustomFieldData
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SubnetPurposeRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"slug",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varSubnetPurposeRequest := _SubnetPurposeRequest{}

	err = json.Unmarshal(data, &varSubnetPurposeRequest)

	if err != nil {
		return err
	}

	*o = SubnetPurposeRequest(varSubnetPurposeRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "slug")
		delete(additionalProperties, "color")
		delete(additionalProperties, "custom_field_data")
		delete(additionalProperties, "tags")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSubnetPurposeRequest struct {
	value *SubnetPurposeRequest
	isSet bool
}

func (v NullableSubnetPurposeRequest) Get() *SubnetPurposeRequest {
	return v.value
}

func (v *NullableSubnetPurposeRequest) Set(val *SubnetPurposeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSubnetPurposeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSubnetPurposeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubnetPurposeRequest(val *SubnetPurposeRequest) *NullableSubnetPurposeRequest {
	return &NullableSubnetPurposeRequest{value: val, isSet: true}
}

func (v NullableSubnetPurposeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubnetPurposeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
