/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.2-Docker-4.0.0 (4.5)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// PluginsAirnityIpamSubnetprefixCreateRequest - struct for PluginsAirnityIpamSubnetprefixCreateRequest
type PluginsAirnityIpamSubnetprefixCreateRequest struct {
	WritableSubnetPrefixRequest        *WritableSubnetPrefixRequest
	ArrayOfWritableSubnetPrefixRequest *[]WritableSubnetPrefixRequest
}

// WritableSubnetPrefixRequestAsPluginsAirnityIpamSubnetprefixCreateRequest is a convenience function that returns WritableSubnetPrefixRequest wrapped in PluginsAirnityIpamSubnetprefixCreateRequest
func WritableSubnetPrefixRequestAsPluginsAirnityIpamSubnetprefixCreateRequest(v *WritableSubnetPrefixRequest) PluginsAirnityIpamSubnetprefixCreateRequest {
	return PluginsAirnityIpamSubnetprefixCreateRequest{
		WritableSubnetPrefixRequest: v,
	}
}

// []WritableSubnetPrefixRequestAsPluginsAirnityIpamSubnetprefixCreateRequest is a convenience function that returns []WritableSubnetPrefixRequest wrapped in PluginsAirnityIpamSubnetprefixCreateRequest
func ArrayOfWritableSubnetPrefixRequestAsPluginsAirnityIpamSubnetprefixCreateRequest(v *[]WritableSubnetPrefixRequest) PluginsAirnityIpamSubnetprefixCreateRequest {
	return PluginsAirnityIpamSubnetprefixCreateRequest{
		ArrayOfWritableSubnetPrefixRequest: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *PluginsAirnityIpamSubnetprefixCreateRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into WritableSubnetPrefixRequest
	err = newStrictDecoder(data).Decode(&dst.WritableSubnetPrefixRequest)
	if err == nil {
		jsonWritableSubnetPrefixRequest, _ := json.Marshal(dst.WritableSubnetPrefixRequest)
		if string(jsonWritableSubnetPrefixRequest) == "{}" { // empty struct
			dst.WritableSubnetPrefixRequest = nil
		} else {
			if err = validator.Validate(dst.WritableSubnetPrefixRequest); err != nil {
				dst.WritableSubnetPrefixRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.WritableSubnetPrefixRequest = nil
	}

	// try to unmarshal data into ArrayOfWritableSubnetPrefixRequest
	err = newStrictDecoder(data).Decode(&dst.ArrayOfWritableSubnetPrefixRequest)
	if err == nil {
		jsonArrayOfWritableSubnetPrefixRequest, _ := json.Marshal(dst.ArrayOfWritableSubnetPrefixRequest)
		if string(jsonArrayOfWritableSubnetPrefixRequest) == "{}" { // empty struct
			dst.ArrayOfWritableSubnetPrefixRequest = nil
		} else {
			if err = validator.Validate(dst.ArrayOfWritableSubnetPrefixRequest); err != nil {
				dst.ArrayOfWritableSubnetPrefixRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.ArrayOfWritableSubnetPrefixRequest = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.WritableSubnetPrefixRequest = nil
		dst.ArrayOfWritableSubnetPrefixRequest = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PluginsAirnityIpamSubnetprefixCreateRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PluginsAirnityIpamSubnetprefixCreateRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PluginsAirnityIpamSubnetprefixCreateRequest) MarshalJSON() ([]byte, error) {
	if src.WritableSubnetPrefixRequest != nil {
		return json.Marshal(&src.WritableSubnetPrefixRequest)
	}

	if src.ArrayOfWritableSubnetPrefixRequest != nil {
		return json.Marshal(&src.ArrayOfWritableSubnetPrefixRequest)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PluginsAirnityIpamSubnetprefixCreateRequest) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.WritableSubnetPrefixRequest != nil {
		return obj.WritableSubnetPrefixRequest
	}

	if obj.ArrayOfWritableSubnetPrefixRequest != nil {
		return obj.ArrayOfWritableSubnetPrefixRequest
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj PluginsAirnityIpamSubnetprefixCreateRequest) GetActualInstanceValue() interface{} {
	if obj.WritableSubnetPrefixRequest != nil {
		return *obj.WritableSubnetPrefixRequest
	}

	if obj.ArrayOfWritableSubnetPrefixRequest != nil {
		return *obj.ArrayOfWritableSubnetPrefixRequest
	}

	// all schemas are nil
	return nil
}

type NullablePluginsAirnityIpamSubnetprefixCreateRequest struct {
	value *PluginsAirnityIpamSubnetprefixCreateRequest
	isSet bool
}

func (v NullablePluginsAirnityIpamSubnetprefixCreateRequest) Get() *PluginsAirnityIpamSubnetprefixCreateRequest {
	return v.value
}

func (v *NullablePluginsAirnityIpamSubnetprefixCreateRequest) Set(val *PluginsAirnityIpamSubnetprefixCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePluginsAirnityIpamSubnetprefixCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePluginsAirnityIpamSubnetprefixCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePluginsAirnityIpamSubnetprefixCreateRequest(val *PluginsAirnityIpamSubnetprefixCreateRequest) *NullablePluginsAirnityIpamSubnetprefixCreateRequest {
	return &NullablePluginsAirnityIpamSubnetprefixCreateRequest{value: val, isSet: true}
}

func (v NullablePluginsAirnityIpamSubnetprefixCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePluginsAirnityIpamSubnetprefixCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
