/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.2-Docker-4.0.0 (4.5)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// checks if the SubnetWithPrefix type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubnetWithPrefix{}

// SubnetWithPrefix Subnet with associated prefixes.
type SubnetWithPrefix struct {
	Id int32 `json:"id"`
	// Name of the Subnet
	Name                 *string                       `json:"name,omitempty" validate:"regexp=^[a-z0-9_-]+$"`
	Purpose              NullableString                `json:"purpose,omitempty"`
	Prefix               NullableSubnetPrefixForSubnet `json:"prefix,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SubnetWithPrefix SubnetWithPrefix

// NewSubnetWithPrefix instantiates a new SubnetWithPrefix object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubnetWithPrefix(id int32) *SubnetWithPrefix {
	this := SubnetWithPrefix{}
	this.Id = id
	return &this
}

// NewSubnetWithPrefixWithDefaults instantiates a new SubnetWithPrefix object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubnetWithPrefixWithDefaults() *SubnetWithPrefix {
	this := SubnetWithPrefix{}
	return &this
}

// GetId returns the Id field value
func (o *SubnetWithPrefix) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SubnetWithPrefix) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SubnetWithPrefix) SetId(v int32) {
	o.Id = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SubnetWithPrefix) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubnetWithPrefix) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SubnetWithPrefix) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SubnetWithPrefix) SetName(v string) {
	o.Name = &v
}

// GetPurpose returns the Purpose field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SubnetWithPrefix) GetPurpose() string {
	if o == nil || IsNil(o.Purpose.Get()) {
		var ret string
		return ret
	}
	return *o.Purpose.Get()
}

// GetPurposeOk returns a tuple with the Purpose field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SubnetWithPrefix) GetPurposeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Purpose.Get(), o.Purpose.IsSet()
}

// HasPurpose returns a boolean if a field has been set.
func (o *SubnetWithPrefix) HasPurpose() bool {
	if o != nil && o.Purpose.IsSet() {
		return true
	}

	return false
}

// SetPurpose gets a reference to the given NullableString and assigns it to the Purpose field.
func (o *SubnetWithPrefix) SetPurpose(v string) {
	o.Purpose.Set(&v)
}

// SetPurposeNil sets the value for Purpose to be an explicit nil
func (o *SubnetWithPrefix) SetPurposeNil() {
	o.Purpose.Set(nil)
}

// UnsetPurpose ensures that no value is present for Purpose, not even an explicit nil
func (o *SubnetWithPrefix) UnsetPurpose() {
	o.Purpose.Unset()
}

// GetPrefix returns the Prefix field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SubnetWithPrefix) GetPrefix() SubnetPrefixForSubnet {
	if o == nil || IsNil(o.Prefix.Get()) {
		var ret SubnetPrefixForSubnet
		return ret
	}
	return *o.Prefix.Get()
}

// GetPrefixOk returns a tuple with the Prefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SubnetWithPrefix) GetPrefixOk() (*SubnetPrefixForSubnet, bool) {
	if o == nil {
		return nil, false
	}
	return o.Prefix.Get(), o.Prefix.IsSet()
}

// HasPrefix returns a boolean if a field has been set.
func (o *SubnetWithPrefix) HasPrefix() bool {
	if o != nil && o.Prefix.IsSet() {
		return true
	}

	return false
}

// SetPrefix gets a reference to the given NullableSubnetPrefixForSubnet and assigns it to the Prefix field.
func (o *SubnetWithPrefix) SetPrefix(v SubnetPrefixForSubnet) {
	o.Prefix.Set(&v)
}

// SetPrefixNil sets the value for Prefix to be an explicit nil
func (o *SubnetWithPrefix) SetPrefixNil() {
	o.Prefix.Set(nil)
}

// UnsetPrefix ensures that no value is present for Prefix, not even an explicit nil
func (o *SubnetWithPrefix) UnsetPrefix() {
	o.Prefix.Unset()
}

func (o SubnetWithPrefix) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubnetWithPrefix) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if o.Purpose.IsSet() {
		toSerialize["purpose"] = o.Purpose.Get()
	}
	if o.Prefix.IsSet() {
		toSerialize["prefix"] = o.Prefix.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SubnetWithPrefix) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varSubnetWithPrefix := _SubnetWithPrefix{}

	err = json.Unmarshal(data, &varSubnetWithPrefix)

	if err != nil {
		return err
	}

	*o = SubnetWithPrefix(varSubnetWithPrefix)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "purpose")
		delete(additionalProperties, "prefix")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSubnetWithPrefix struct {
	value *SubnetWithPrefix
	isSet bool
}

func (v NullableSubnetWithPrefix) Get() *SubnetWithPrefix {
	return v.value
}

func (v *NullableSubnetWithPrefix) Set(val *SubnetWithPrefix) {
	v.value = val
	v.isSet = true
}

func (v NullableSubnetWithPrefix) IsSet() bool {
	return v.isSet
}

func (v *NullableSubnetWithPrefix) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubnetWithPrefix(val *SubnetWithPrefix) *NullableSubnetWithPrefix {
	return &NullableSubnetWithPrefix{value: val, isSet: true}
}

func (v NullableSubnetWithPrefix) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubnetWithPrefix) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
