/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.1-Docker-3.4.2 (4.5)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
)

// checks if the PatchedVPCRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchedVPCRequest{}

// PatchedVPCRequest Adds support for custom fields and tags.
type PatchedVPCRequest struct {
	// Name of the VPC
	Name                 *string                            `json:"name,omitempty" validate:"regexp=^[a-z0-9_-]+$"`
	Environment          NullableBriefVPCRequestEnvironment `json:"environment,omitempty"`
	CustomFieldData      interface{}                        `json:"custom_field_data,omitempty"`
	Tags                 []NestedTagRequest                 `json:"tags,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PatchedVPCRequest PatchedVPCRequest

// NewPatchedVPCRequest instantiates a new PatchedVPCRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchedVPCRequest() *PatchedVPCRequest {
	this := PatchedVPCRequest{}
	return &this
}

// NewPatchedVPCRequestWithDefaults instantiates a new PatchedVPCRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchedVPCRequestWithDefaults() *PatchedVPCRequest {
	this := PatchedVPCRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PatchedVPCRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedVPCRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PatchedVPCRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PatchedVPCRequest) SetName(v string) {
	o.Name = &v
}

// GetEnvironment returns the Environment field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedVPCRequest) GetEnvironment() BriefVPCRequestEnvironment {
	if o == nil || IsNil(o.Environment.Get()) {
		var ret BriefVPCRequestEnvironment
		return ret
	}
	return *o.Environment.Get()
}

// GetEnvironmentOk returns a tuple with the Environment field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedVPCRequest) GetEnvironmentOk() (*BriefVPCRequestEnvironment, bool) {
	if o == nil {
		return nil, false
	}
	return o.Environment.Get(), o.Environment.IsSet()
}

// HasEnvironment returns a boolean if a field has been set.
func (o *PatchedVPCRequest) HasEnvironment() bool {
	if o != nil && o.Environment.IsSet() {
		return true
	}

	return false
}

// SetEnvironment gets a reference to the given NullableBriefVPCRequestEnvironment and assigns it to the Environment field.
func (o *PatchedVPCRequest) SetEnvironment(v BriefVPCRequestEnvironment) {
	o.Environment.Set(&v)
}

// SetEnvironmentNil sets the value for Environment to be an explicit nil
func (o *PatchedVPCRequest) SetEnvironmentNil() {
	o.Environment.Set(nil)
}

// UnsetEnvironment ensures that no value is present for Environment, not even an explicit nil
func (o *PatchedVPCRequest) UnsetEnvironment() {
	o.Environment.Unset()
}

// GetCustomFieldData returns the CustomFieldData field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedVPCRequest) GetCustomFieldData() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.CustomFieldData
}

// GetCustomFieldDataOk returns a tuple with the CustomFieldData field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedVPCRequest) GetCustomFieldDataOk() (*interface{}, bool) {
	if o == nil || IsNil(o.CustomFieldData) {
		return nil, false
	}
	return &o.CustomFieldData, true
}

// HasCustomFieldData returns a boolean if a field has been set.
func (o *PatchedVPCRequest) HasCustomFieldData() bool {
	if o != nil && !IsNil(o.CustomFieldData) {
		return true
	}

	return false
}

// SetCustomFieldData gets a reference to the given interface{} and assigns it to the CustomFieldData field.
func (o *PatchedVPCRequest) SetCustomFieldData(v interface{}) {
	o.CustomFieldData = v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *PatchedVPCRequest) GetTags() []NestedTagRequest {
	if o == nil || IsNil(o.Tags) {
		var ret []NestedTagRequest
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedVPCRequest) GetTagsOk() ([]NestedTagRequest, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *PatchedVPCRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []NestedTagRequest and assigns it to the Tags field.
func (o *PatchedVPCRequest) SetTags(v []NestedTagRequest) {
	o.Tags = v
}

func (o PatchedVPCRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchedVPCRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if o.Environment.IsSet() {
		toSerialize["environment"] = o.Environment.Get()
	}
	if o.CustomFieldData != nil {
		toSerialize["custom_field_data"] = o.CustomFieldData
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PatchedVPCRequest) UnmarshalJSON(data []byte) (err error) {
	varPatchedVPCRequest := _PatchedVPCRequest{}

	err = json.Unmarshal(data, &varPatchedVPCRequest)

	if err != nil {
		return err
	}

	*o = PatchedVPCRequest(varPatchedVPCRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "environment")
		delete(additionalProperties, "custom_field_data")
		delete(additionalProperties, "tags")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePatchedVPCRequest struct {
	value *PatchedVPCRequest
	isSet bool
}

func (v NullablePatchedVPCRequest) Get() *PatchedVPCRequest {
	return v.value
}

func (v *NullablePatchedVPCRequest) Set(val *PatchedVPCRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedVPCRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedVPCRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedVPCRequest(val *PatchedVPCRequest) *NullablePatchedVPCRequest {
	return &NullablePatchedVPCRequest{value: val, isSet: true}
}

func (v NullablePatchedVPCRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedVPCRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
