/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.2-Docker-4.0.0 (4.5)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
)

// checks if the AvailablePrefixIPRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AvailablePrefixIPRequest{}

// AvailablePrefixIPRequest Representation of an IP address which does not exist in the database. Used for get_first_available_ip() functionality.  Note: - `address` contains the IP without mask (e.g., \"10.0.1.5\") - `mask_length` is always 32 for IPv4 or 128 for IPv6 (host address) - To get the full CIDR notation, combine: f\"{address}/{mask_length}\"
type AvailablePrefixIPRequest struct {
	Description          *string `json:"description,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AvailablePrefixIPRequest AvailablePrefixIPRequest

// NewAvailablePrefixIPRequest instantiates a new AvailablePrefixIPRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAvailablePrefixIPRequest() *AvailablePrefixIPRequest {
	this := AvailablePrefixIPRequest{}
	return &this
}

// NewAvailablePrefixIPRequestWithDefaults instantiates a new AvailablePrefixIPRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAvailablePrefixIPRequestWithDefaults() *AvailablePrefixIPRequest {
	this := AvailablePrefixIPRequest{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *AvailablePrefixIPRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AvailablePrefixIPRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *AvailablePrefixIPRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *AvailablePrefixIPRequest) SetDescription(v string) {
	o.Description = &v
}

func (o AvailablePrefixIPRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AvailablePrefixIPRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AvailablePrefixIPRequest) UnmarshalJSON(data []byte) (err error) {
	varAvailablePrefixIPRequest := _AvailablePrefixIPRequest{}

	err = json.Unmarshal(data, &varAvailablePrefixIPRequest)

	if err != nil {
		return err
	}

	*o = AvailablePrefixIPRequest(varAvailablePrefixIPRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "description")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAvailablePrefixIPRequest struct {
	value *AvailablePrefixIPRequest
	isSet bool
}

func (v NullableAvailablePrefixIPRequest) Get() *AvailablePrefixIPRequest {
	return v.value
}

func (v *NullableAvailablePrefixIPRequest) Set(val *AvailablePrefixIPRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAvailablePrefixIPRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAvailablePrefixIPRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAvailablePrefixIPRequest(val *AvailablePrefixIPRequest) *NullableAvailablePrefixIPRequest {
	return &NullableAvailablePrefixIPRequest{value: val, isSet: true}
}

func (v NullableAvailablePrefixIPRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAvailablePrefixIPRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
