/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.2-Docker-4.0.0 (4.5)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// PatchedSubnetRequestVpc - struct for PatchedSubnetRequestVpc
type PatchedSubnetRequestVpc struct {
	BriefNestedVPCRequest *BriefNestedVPCRequest
	Int32                 *int32
}

// BriefNestedVPCRequestAsPatchedSubnetRequestVpc is a convenience function that returns BriefNestedVPCRequest wrapped in PatchedSubnetRequestVpc
func BriefNestedVPCRequestAsPatchedSubnetRequestVpc(v *BriefNestedVPCRequest) PatchedSubnetRequestVpc {
	return PatchedSubnetRequestVpc{
		BriefNestedVPCRequest: v,
	}
}

// int32AsPatchedSubnetRequestVpc is a convenience function that returns int32 wrapped in PatchedSubnetRequestVpc
func Int32AsPatchedSubnetRequestVpc(v *int32) PatchedSubnetRequestVpc {
	return PatchedSubnetRequestVpc{
		Int32: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *PatchedSubnetRequestVpc) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	match := 0
	// try to unmarshal data into BriefNestedVPCRequest
	err = newStrictDecoder(data).Decode(&dst.BriefNestedVPCRequest)
	if err == nil {
		jsonBriefNestedVPCRequest, _ := json.Marshal(dst.BriefNestedVPCRequest)
		if string(jsonBriefNestedVPCRequest) == "{}" { // empty struct
			dst.BriefNestedVPCRequest = nil
		} else {
			if err = validator.Validate(dst.BriefNestedVPCRequest); err != nil {
				dst.BriefNestedVPCRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.BriefNestedVPCRequest = nil
	}

	// try to unmarshal data into Int32
	err = newStrictDecoder(data).Decode(&dst.Int32)
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			if err = validator.Validate(dst.Int32); err != nil {
				dst.Int32 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Int32 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.BriefNestedVPCRequest = nil
		dst.Int32 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PatchedSubnetRequestVpc)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PatchedSubnetRequestVpc)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PatchedSubnetRequestVpc) MarshalJSON() ([]byte, error) {
	if src.BriefNestedVPCRequest != nil {
		return json.Marshal(&src.BriefNestedVPCRequest)
	}

	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PatchedSubnetRequestVpc) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.BriefNestedVPCRequest != nil {
		return obj.BriefNestedVPCRequest
	}

	if obj.Int32 != nil {
		return obj.Int32
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj PatchedSubnetRequestVpc) GetActualInstanceValue() interface{} {
	if obj.BriefNestedVPCRequest != nil {
		return *obj.BriefNestedVPCRequest
	}

	if obj.Int32 != nil {
		return *obj.Int32
	}

	// all schemas are nil
	return nil
}

type NullablePatchedSubnetRequestVpc struct {
	value *PatchedSubnetRequestVpc
	isSet bool
}

func (v NullablePatchedSubnetRequestVpc) Get() *PatchedSubnetRequestVpc {
	return v.value
}

func (v *NullablePatchedSubnetRequestVpc) Set(val *PatchedSubnetRequestVpc) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedSubnetRequestVpc) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedSubnetRequestVpc) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedSubnetRequestVpc(val *PatchedSubnetRequestVpc) *NullablePatchedSubnetRequestVpc {
	return &NullablePatchedSubnetRequestVpc{value: val, isSet: true}
}

func (v NullablePatchedSubnetRequestVpc) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedSubnetRequestVpc) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
