/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.2-Docker-4.0.0 (4.5)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// PatchedSubnetRequestRegion - struct for PatchedSubnetRequestRegion
type PatchedSubnetRequestRegion struct {
	BriefRegionRequest *BriefRegionRequest
	Int32              *int32
}

// BriefRegionRequestAsPatchedSubnetRequestRegion is a convenience function that returns BriefRegionRequest wrapped in PatchedSubnetRequestRegion
func BriefRegionRequestAsPatchedSubnetRequestRegion(v *BriefRegionRequest) PatchedSubnetRequestRegion {
	return PatchedSubnetRequestRegion{
		BriefRegionRequest: v,
	}
}

// int32AsPatchedSubnetRequestRegion is a convenience function that returns int32 wrapped in PatchedSubnetRequestRegion
func Int32AsPatchedSubnetRequestRegion(v *int32) PatchedSubnetRequestRegion {
	return PatchedSubnetRequestRegion{
		Int32: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *PatchedSubnetRequestRegion) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	match := 0
	// try to unmarshal data into BriefRegionRequest
	err = newStrictDecoder(data).Decode(&dst.BriefRegionRequest)
	if err == nil {
		jsonBriefRegionRequest, _ := json.Marshal(dst.BriefRegionRequest)
		if string(jsonBriefRegionRequest) == "{}" { // empty struct
			dst.BriefRegionRequest = nil
		} else {
			if err = validator.Validate(dst.BriefRegionRequest); err != nil {
				dst.BriefRegionRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.BriefRegionRequest = nil
	}

	// try to unmarshal data into Int32
	err = newStrictDecoder(data).Decode(&dst.Int32)
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			if err = validator.Validate(dst.Int32); err != nil {
				dst.Int32 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Int32 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.BriefRegionRequest = nil
		dst.Int32 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PatchedSubnetRequestRegion)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PatchedSubnetRequestRegion)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PatchedSubnetRequestRegion) MarshalJSON() ([]byte, error) {
	if src.BriefRegionRequest != nil {
		return json.Marshal(&src.BriefRegionRequest)
	}

	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PatchedSubnetRequestRegion) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.BriefRegionRequest != nil {
		return obj.BriefRegionRequest
	}

	if obj.Int32 != nil {
		return obj.Int32
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj PatchedSubnetRequestRegion) GetActualInstanceValue() interface{} {
	if obj.BriefRegionRequest != nil {
		return *obj.BriefRegionRequest
	}

	if obj.Int32 != nil {
		return *obj.Int32
	}

	// all schemas are nil
	return nil
}

type NullablePatchedSubnetRequestRegion struct {
	value *PatchedSubnetRequestRegion
	isSet bool
}

func (v NullablePatchedSubnetRequestRegion) Get() *PatchedSubnetRequestRegion {
	return v.value
}

func (v *NullablePatchedSubnetRequestRegion) Set(val *PatchedSubnetRequestRegion) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedSubnetRequestRegion) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedSubnetRequestRegion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedSubnetRequestRegion(val *PatchedSubnetRequestRegion) *NullablePatchedSubnetRequestRegion {
	return &NullablePatchedSubnetRequestRegion{value: val, isSet: true}
}

func (v NullablePatchedSubnetRequestRegion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedSubnetRequestRegion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
