/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.2-Docker-4.0.0 (4.5)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// PatchedWritableSubnetPrefixRequestStatus Operational status of this prefix  * `container` - Container * `active` - Active * `reserved` - Reserved * `deprecated` - Deprecated
type PatchedWritableSubnetPrefixRequestStatus string

// List of PatchedWritableSubnetPrefixRequest_status
const (
	PATCHEDWRITABLESUBNETPREFIXREQUESTSTATUS_CONTAINER  PatchedWritableSubnetPrefixRequestStatus = "container"
	PATCHEDWRITABLESUBNETPREFIXREQUESTSTATUS_ACTIVE     PatchedWritableSubnetPrefixRequestStatus = "active"
	PATCHEDWRITABLESUBNETPREFIXREQUESTSTATUS_RESERVED   PatchedWritableSubnetPrefixRequestStatus = "reserved"
	PATCHEDWRITABLESUBNETPREFIXREQUESTSTATUS_DEPRECATED PatchedWritableSubnetPrefixRequestStatus = "deprecated"
)

// All allowed values of PatchedWritableSubnetPrefixRequestStatus enum
var AllowedPatchedWritableSubnetPrefixRequestStatusEnumValues = []PatchedWritableSubnetPrefixRequestStatus{
	"container",
	"active",
	"reserved",
	"deprecated",
}

func (v *PatchedWritableSubnetPrefixRequestStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PatchedWritableSubnetPrefixRequestStatus(value)
	for _, existing := range AllowedPatchedWritableSubnetPrefixRequestStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PatchedWritableSubnetPrefixRequestStatus", value)
}

// NewPatchedWritableSubnetPrefixRequestStatusFromValue returns a pointer to a valid PatchedWritableSubnetPrefixRequestStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPatchedWritableSubnetPrefixRequestStatusFromValue(v string) (*PatchedWritableSubnetPrefixRequestStatus, error) {
	ev := PatchedWritableSubnetPrefixRequestStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PatchedWritableSubnetPrefixRequestStatus: valid values are %v", v, AllowedPatchedWritableSubnetPrefixRequestStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PatchedWritableSubnetPrefixRequestStatus) IsValid() bool {
	for _, existing := range AllowedPatchedWritableSubnetPrefixRequestStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PatchedWritableSubnetPrefixRequest_status value
func (v PatchedWritableSubnetPrefixRequestStatus) Ptr() *PatchedWritableSubnetPrefixRequestStatus {
	return &v
}

type NullablePatchedWritableSubnetPrefixRequestStatus struct {
	value *PatchedWritableSubnetPrefixRequestStatus
	isSet bool
}

func (v NullablePatchedWritableSubnetPrefixRequestStatus) Get() *PatchedWritableSubnetPrefixRequestStatus {
	return v.value
}

func (v *NullablePatchedWritableSubnetPrefixRequestStatus) Set(val *PatchedWritableSubnetPrefixRequestStatus) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedWritableSubnetPrefixRequestStatus) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedWritableSubnetPrefixRequestStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedWritableSubnetPrefixRequestStatus(val *PatchedWritableSubnetPrefixRequestStatus) *NullablePatchedWritableSubnetPrefixRequestStatus {
	return &NullablePatchedWritableSubnetPrefixRequestStatus{value: val, isSet: true}
}

func (v NullablePatchedWritableSubnetPrefixRequestStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedWritableSubnetPrefixRequestStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
