/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.1-Docker-3.4.2 (4.5)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// checks if the SubnetIPAddressRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubnetIPAddressRequest{}

// SubnetIPAddressRequest Serializer for SubnetIPAddress model.
type SubnetIPAddressRequest struct {
	Address string                                       `json:"address"`
	Vpc     NullablePatchedSubnetIPAddressRequestVpc     `json:"vpc,omitempty"`
	Country NullablePatchedSubnetIPAddressRequestCountry `json:"country,omitempty"`
	// The subnet prefix this IP belongs to
	SubnetPrefix int32                                       `json:"subnet_prefix"`
	Tenant       NullablePatchedSubnetIPAddressRequestTenant `json:"tenant,omitempty"`
	Status       *PatchedSubnetIPAddressRequestStatus        `json:"status,omitempty"`
	Role         *PatchedSubnetIPAddressRequestRole          `json:"role,omitempty"`
	NatInside    NullableNestedSubnetIPAddressRequest        `json:"nat_inside,omitempty"`
	// Hostname or FQDN (not case-sensitive)
	DnsName              *string                `json:"dns_name,omitempty" validate:"regexp=^([0-9A-Za-z_-]+|\\\\*)(\\\\.[0-9A-Za-z_-]+)*\\\\.?$"`
	Description          *string                `json:"description,omitempty"`
	Comments             *string                `json:"comments,omitempty"`
	Tags                 []NestedTagRequest     `json:"tags,omitempty"`
	CustomFields         map[string]interface{} `json:"custom_fields,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SubnetIPAddressRequest SubnetIPAddressRequest

// NewSubnetIPAddressRequest instantiates a new SubnetIPAddressRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubnetIPAddressRequest(address string, subnetPrefix int32) *SubnetIPAddressRequest {
	this := SubnetIPAddressRequest{}
	this.Address = address
	this.SubnetPrefix = subnetPrefix
	return &this
}

// NewSubnetIPAddressRequestWithDefaults instantiates a new SubnetIPAddressRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubnetIPAddressRequestWithDefaults() *SubnetIPAddressRequest {
	this := SubnetIPAddressRequest{}
	return &this
}

// GetAddress returns the Address field value
func (o *SubnetIPAddressRequest) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *SubnetIPAddressRequest) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *SubnetIPAddressRequest) SetAddress(v string) {
	o.Address = v
}

// GetVpc returns the Vpc field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SubnetIPAddressRequest) GetVpc() PatchedSubnetIPAddressRequestVpc {
	if o == nil || IsNil(o.Vpc.Get()) {
		var ret PatchedSubnetIPAddressRequestVpc
		return ret
	}
	return *o.Vpc.Get()
}

// GetVpcOk returns a tuple with the Vpc field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SubnetIPAddressRequest) GetVpcOk() (*PatchedSubnetIPAddressRequestVpc, bool) {
	if o == nil {
		return nil, false
	}
	return o.Vpc.Get(), o.Vpc.IsSet()
}

// HasVpc returns a boolean if a field has been set.
func (o *SubnetIPAddressRequest) HasVpc() bool {
	if o != nil && o.Vpc.IsSet() {
		return true
	}

	return false
}

// SetVpc gets a reference to the given NullablePatchedSubnetIPAddressRequestVpc and assigns it to the Vpc field.
func (o *SubnetIPAddressRequest) SetVpc(v PatchedSubnetIPAddressRequestVpc) {
	o.Vpc.Set(&v)
}

// SetVpcNil sets the value for Vpc to be an explicit nil
func (o *SubnetIPAddressRequest) SetVpcNil() {
	o.Vpc.Set(nil)
}

// UnsetVpc ensures that no value is present for Vpc, not even an explicit nil
func (o *SubnetIPAddressRequest) UnsetVpc() {
	o.Vpc.Unset()
}

// GetCountry returns the Country field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SubnetIPAddressRequest) GetCountry() PatchedSubnetIPAddressRequestCountry {
	if o == nil || IsNil(o.Country.Get()) {
		var ret PatchedSubnetIPAddressRequestCountry
		return ret
	}
	return *o.Country.Get()
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SubnetIPAddressRequest) GetCountryOk() (*PatchedSubnetIPAddressRequestCountry, bool) {
	if o == nil {
		return nil, false
	}
	return o.Country.Get(), o.Country.IsSet()
}

// HasCountry returns a boolean if a field has been set.
func (o *SubnetIPAddressRequest) HasCountry() bool {
	if o != nil && o.Country.IsSet() {
		return true
	}

	return false
}

// SetCountry gets a reference to the given NullablePatchedSubnetIPAddressRequestCountry and assigns it to the Country field.
func (o *SubnetIPAddressRequest) SetCountry(v PatchedSubnetIPAddressRequestCountry) {
	o.Country.Set(&v)
}

// SetCountryNil sets the value for Country to be an explicit nil
func (o *SubnetIPAddressRequest) SetCountryNil() {
	o.Country.Set(nil)
}

// UnsetCountry ensures that no value is present for Country, not even an explicit nil
func (o *SubnetIPAddressRequest) UnsetCountry() {
	o.Country.Unset()
}

// GetSubnetPrefix returns the SubnetPrefix field value
func (o *SubnetIPAddressRequest) GetSubnetPrefix() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SubnetPrefix
}

// GetSubnetPrefixOk returns a tuple with the SubnetPrefix field value
// and a boolean to check if the value has been set.
func (o *SubnetIPAddressRequest) GetSubnetPrefixOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubnetPrefix, true
}

// SetSubnetPrefix sets field value
func (o *SubnetIPAddressRequest) SetSubnetPrefix(v int32) {
	o.SubnetPrefix = v
}

// GetTenant returns the Tenant field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SubnetIPAddressRequest) GetTenant() PatchedSubnetIPAddressRequestTenant {
	if o == nil || IsNil(o.Tenant.Get()) {
		var ret PatchedSubnetIPAddressRequestTenant
		return ret
	}
	return *o.Tenant.Get()
}

// GetTenantOk returns a tuple with the Tenant field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SubnetIPAddressRequest) GetTenantOk() (*PatchedSubnetIPAddressRequestTenant, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tenant.Get(), o.Tenant.IsSet()
}

// HasTenant returns a boolean if a field has been set.
func (o *SubnetIPAddressRequest) HasTenant() bool {
	if o != nil && o.Tenant.IsSet() {
		return true
	}

	return false
}

// SetTenant gets a reference to the given NullablePatchedSubnetIPAddressRequestTenant and assigns it to the Tenant field.
func (o *SubnetIPAddressRequest) SetTenant(v PatchedSubnetIPAddressRequestTenant) {
	o.Tenant.Set(&v)
}

// SetTenantNil sets the value for Tenant to be an explicit nil
func (o *SubnetIPAddressRequest) SetTenantNil() {
	o.Tenant.Set(nil)
}

// UnsetTenant ensures that no value is present for Tenant, not even an explicit nil
func (o *SubnetIPAddressRequest) UnsetTenant() {
	o.Tenant.Unset()
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *SubnetIPAddressRequest) GetStatus() PatchedSubnetIPAddressRequestStatus {
	if o == nil || IsNil(o.Status) {
		var ret PatchedSubnetIPAddressRequestStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubnetIPAddressRequest) GetStatusOk() (*PatchedSubnetIPAddressRequestStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *SubnetIPAddressRequest) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given PatchedSubnetIPAddressRequestStatus and assigns it to the Status field.
func (o *SubnetIPAddressRequest) SetStatus(v PatchedSubnetIPAddressRequestStatus) {
	o.Status = &v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *SubnetIPAddressRequest) GetRole() PatchedSubnetIPAddressRequestRole {
	if o == nil || IsNil(o.Role) {
		var ret PatchedSubnetIPAddressRequestRole
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubnetIPAddressRequest) GetRoleOk() (*PatchedSubnetIPAddressRequestRole, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *SubnetIPAddressRequest) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given PatchedSubnetIPAddressRequestRole and assigns it to the Role field.
func (o *SubnetIPAddressRequest) SetRole(v PatchedSubnetIPAddressRequestRole) {
	o.Role = &v
}

// GetNatInside returns the NatInside field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SubnetIPAddressRequest) GetNatInside() NestedSubnetIPAddressRequest {
	if o == nil || IsNil(o.NatInside.Get()) {
		var ret NestedSubnetIPAddressRequest
		return ret
	}
	return *o.NatInside.Get()
}

// GetNatInsideOk returns a tuple with the NatInside field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SubnetIPAddressRequest) GetNatInsideOk() (*NestedSubnetIPAddressRequest, bool) {
	if o == nil {
		return nil, false
	}
	return o.NatInside.Get(), o.NatInside.IsSet()
}

// HasNatInside returns a boolean if a field has been set.
func (o *SubnetIPAddressRequest) HasNatInside() bool {
	if o != nil && o.NatInside.IsSet() {
		return true
	}

	return false
}

// SetNatInside gets a reference to the given NullableNestedSubnetIPAddressRequest and assigns it to the NatInside field.
func (o *SubnetIPAddressRequest) SetNatInside(v NestedSubnetIPAddressRequest) {
	o.NatInside.Set(&v)
}

// SetNatInsideNil sets the value for NatInside to be an explicit nil
func (o *SubnetIPAddressRequest) SetNatInsideNil() {
	o.NatInside.Set(nil)
}

// UnsetNatInside ensures that no value is present for NatInside, not even an explicit nil
func (o *SubnetIPAddressRequest) UnsetNatInside() {
	o.NatInside.Unset()
}

// GetDnsName returns the DnsName field value if set, zero value otherwise.
func (o *SubnetIPAddressRequest) GetDnsName() string {
	if o == nil || IsNil(o.DnsName) {
		var ret string
		return ret
	}
	return *o.DnsName
}

// GetDnsNameOk returns a tuple with the DnsName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubnetIPAddressRequest) GetDnsNameOk() (*string, bool) {
	if o == nil || IsNil(o.DnsName) {
		return nil, false
	}
	return o.DnsName, true
}

// HasDnsName returns a boolean if a field has been set.
func (o *SubnetIPAddressRequest) HasDnsName() bool {
	if o != nil && !IsNil(o.DnsName) {
		return true
	}

	return false
}

// SetDnsName gets a reference to the given string and assigns it to the DnsName field.
func (o *SubnetIPAddressRequest) SetDnsName(v string) {
	o.DnsName = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *SubnetIPAddressRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubnetIPAddressRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *SubnetIPAddressRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *SubnetIPAddressRequest) SetDescription(v string) {
	o.Description = &v
}

// GetComments returns the Comments field value if set, zero value otherwise.
func (o *SubnetIPAddressRequest) GetComments() string {
	if o == nil || IsNil(o.Comments) {
		var ret string
		return ret
	}
	return *o.Comments
}

// GetCommentsOk returns a tuple with the Comments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubnetIPAddressRequest) GetCommentsOk() (*string, bool) {
	if o == nil || IsNil(o.Comments) {
		return nil, false
	}
	return o.Comments, true
}

// HasComments returns a boolean if a field has been set.
func (o *SubnetIPAddressRequest) HasComments() bool {
	if o != nil && !IsNil(o.Comments) {
		return true
	}

	return false
}

// SetComments gets a reference to the given string and assigns it to the Comments field.
func (o *SubnetIPAddressRequest) SetComments(v string) {
	o.Comments = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *SubnetIPAddressRequest) GetTags() []NestedTagRequest {
	if o == nil || IsNil(o.Tags) {
		var ret []NestedTagRequest
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubnetIPAddressRequest) GetTagsOk() ([]NestedTagRequest, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *SubnetIPAddressRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []NestedTagRequest and assigns it to the Tags field.
func (o *SubnetIPAddressRequest) SetTags(v []NestedTagRequest) {
	o.Tags = v
}

// GetCustomFields returns the CustomFields field value if set, zero value otherwise.
func (o *SubnetIPAddressRequest) GetCustomFields() map[string]interface{} {
	if o == nil || IsNil(o.CustomFields) {
		var ret map[string]interface{}
		return ret
	}
	return o.CustomFields
}

// GetCustomFieldsOk returns a tuple with the CustomFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubnetIPAddressRequest) GetCustomFieldsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CustomFields) {
		return map[string]interface{}{}, false
	}
	return o.CustomFields, true
}

// HasCustomFields returns a boolean if a field has been set.
func (o *SubnetIPAddressRequest) HasCustomFields() bool {
	if o != nil && !IsNil(o.CustomFields) {
		return true
	}

	return false
}

// SetCustomFields gets a reference to the given map[string]interface{} and assigns it to the CustomFields field.
func (o *SubnetIPAddressRequest) SetCustomFields(v map[string]interface{}) {
	o.CustomFields = v
}

func (o SubnetIPAddressRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubnetIPAddressRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	if o.Vpc.IsSet() {
		toSerialize["vpc"] = o.Vpc.Get()
	}
	if o.Country.IsSet() {
		toSerialize["country"] = o.Country.Get()
	}
	toSerialize["subnet_prefix"] = o.SubnetPrefix
	if o.Tenant.IsSet() {
		toSerialize["tenant"] = o.Tenant.Get()
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	if o.NatInside.IsSet() {
		toSerialize["nat_inside"] = o.NatInside.Get()
	}
	if !IsNil(o.DnsName) {
		toSerialize["dns_name"] = o.DnsName
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Comments) {
		toSerialize["comments"] = o.Comments
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.CustomFields) {
		toSerialize["custom_fields"] = o.CustomFields
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SubnetIPAddressRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
		"subnet_prefix",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varSubnetIPAddressRequest := _SubnetIPAddressRequest{}

	err = json.Unmarshal(data, &varSubnetIPAddressRequest)

	if err != nil {
		return err
	}

	*o = SubnetIPAddressRequest(varSubnetIPAddressRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "address")
		delete(additionalProperties, "vpc")
		delete(additionalProperties, "country")
		delete(additionalProperties, "subnet_prefix")
		delete(additionalProperties, "tenant")
		delete(additionalProperties, "status")
		delete(additionalProperties, "role")
		delete(additionalProperties, "nat_inside")
		delete(additionalProperties, "dns_name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "comments")
		delete(additionalProperties, "tags")
		delete(additionalProperties, "custom_fields")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSubnetIPAddressRequest struct {
	value *SubnetIPAddressRequest
	isSet bool
}

func (v NullableSubnetIPAddressRequest) Get() *SubnetIPAddressRequest {
	return v.value
}

func (v *NullableSubnetIPAddressRequest) Set(val *SubnetIPAddressRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSubnetIPAddressRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSubnetIPAddressRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubnetIPAddressRequest(val *SubnetIPAddressRequest) *NullableSubnetIPAddressRequest {
	return &NullableSubnetIPAddressRequest{value: val, isSet: true}
}

func (v NullableSubnetIPAddressRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubnetIPAddressRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
