/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.1-Docker-3.4.2 (4.5)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
)

// checks if the NestedSubnetPrefixStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NestedSubnetPrefixStatus{}

// NestedSubnetPrefixStatus struct for NestedSubnetPrefixStatus
type NestedSubnetPrefixStatus struct {
	Value                *NestedSubnetPrefixStatusValue `json:"value,omitempty"`
	Label                *NestedSubnetPrefixStatusLabel `json:"label,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _NestedSubnetPrefixStatus NestedSubnetPrefixStatus

// NewNestedSubnetPrefixStatus instantiates a new NestedSubnetPrefixStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNestedSubnetPrefixStatus() *NestedSubnetPrefixStatus {
	this := NestedSubnetPrefixStatus{}
	return &this
}

// NewNestedSubnetPrefixStatusWithDefaults instantiates a new NestedSubnetPrefixStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNestedSubnetPrefixStatusWithDefaults() *NestedSubnetPrefixStatus {
	this := NestedSubnetPrefixStatus{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *NestedSubnetPrefixStatus) GetValue() NestedSubnetPrefixStatusValue {
	if o == nil || IsNil(o.Value) {
		var ret NestedSubnetPrefixStatusValue
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NestedSubnetPrefixStatus) GetValueOk() (*NestedSubnetPrefixStatusValue, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *NestedSubnetPrefixStatus) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given NestedSubnetPrefixStatusValue and assigns it to the Value field.
func (o *NestedSubnetPrefixStatus) SetValue(v NestedSubnetPrefixStatusValue) {
	o.Value = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *NestedSubnetPrefixStatus) GetLabel() NestedSubnetPrefixStatusLabel {
	if o == nil || IsNil(o.Label) {
		var ret NestedSubnetPrefixStatusLabel
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NestedSubnetPrefixStatus) GetLabelOk() (*NestedSubnetPrefixStatusLabel, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *NestedSubnetPrefixStatus) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given NestedSubnetPrefixStatusLabel and assigns it to the Label field.
func (o *NestedSubnetPrefixStatus) SetLabel(v NestedSubnetPrefixStatusLabel) {
	o.Label = &v
}

func (o NestedSubnetPrefixStatus) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NestedSubnetPrefixStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NestedSubnetPrefixStatus) UnmarshalJSON(data []byte) (err error) {
	varNestedSubnetPrefixStatus := _NestedSubnetPrefixStatus{}

	err = json.Unmarshal(data, &varNestedSubnetPrefixStatus)

	if err != nil {
		return err
	}

	*o = NestedSubnetPrefixStatus(varNestedSubnetPrefixStatus)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "value")
		delete(additionalProperties, "label")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNestedSubnetPrefixStatus struct {
	value *NestedSubnetPrefixStatus
	isSet bool
}

func (v NullableNestedSubnetPrefixStatus) Get() *NestedSubnetPrefixStatus {
	return v.value
}

func (v *NullableNestedSubnetPrefixStatus) Set(val *NestedSubnetPrefixStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableNestedSubnetPrefixStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableNestedSubnetPrefixStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNestedSubnetPrefixStatus(val *NestedSubnetPrefixStatus) *NullableNestedSubnetPrefixStatus {
	return &NullableNestedSubnetPrefixStatus{value: val, isSet: true}
}

func (v NullableNestedSubnetPrefixStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNestedSubnetPrefixStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
