/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.2-Docker-4.0.0 (4.5)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// checks if the NestedSubnetPrefix type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NestedSubnetPrefix{}

// NestedSubnetPrefix Nested SubnetPrefix representation (read-only). Used for displaying prefixes in responses.
type NestedSubnetPrefix struct {
	Id      int32  `json:"id"`
	Url     string `json:"url"`
	Display string `json:"display"`
	Prefix  string `json:"prefix"`
	// Name of the Subnet
	Label *string `json:"label,omitempty" validate:"regexp=^[a-z0-9_-]+$"`
	// Set Prefix subnet as secondary
	IsSecondary *bool `json:"is_secondary,omitempty"`
	// Automatically reserve IP addresses based on plugin configuration
	AutoReserveIps *bool `json:"auto_reserve_ips,omitempty"`
	// Treat this prefix as fully utilized
	MarkUtilized         *bool                     `json:"mark_utilized,omitempty"`
	Status               *NestedSubnetPrefixStatus `json:"status,omitempty"`
	Description          *string                   `json:"description,omitempty"`
	Comments             *string                   `json:"comments,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _NestedSubnetPrefix NestedSubnetPrefix

// NewNestedSubnetPrefix instantiates a new NestedSubnetPrefix object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNestedSubnetPrefix(id int32, url string, display string, prefix string) *NestedSubnetPrefix {
	this := NestedSubnetPrefix{}
	this.Id = id
	this.Url = url
	this.Display = display
	this.Prefix = prefix
	return &this
}

// NewNestedSubnetPrefixWithDefaults instantiates a new NestedSubnetPrefix object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNestedSubnetPrefixWithDefaults() *NestedSubnetPrefix {
	this := NestedSubnetPrefix{}
	return &this
}

// GetId returns the Id field value
func (o *NestedSubnetPrefix) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *NestedSubnetPrefix) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *NestedSubnetPrefix) SetId(v int32) {
	o.Id = v
}

// GetUrl returns the Url field value
func (o *NestedSubnetPrefix) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *NestedSubnetPrefix) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *NestedSubnetPrefix) SetUrl(v string) {
	o.Url = v
}

// GetDisplay returns the Display field value
func (o *NestedSubnetPrefix) GetDisplay() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Display
}

// GetDisplayOk returns a tuple with the Display field value
// and a boolean to check if the value has been set.
func (o *NestedSubnetPrefix) GetDisplayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Display, true
}

// SetDisplay sets field value
func (o *NestedSubnetPrefix) SetDisplay(v string) {
	o.Display = v
}

// GetPrefix returns the Prefix field value
func (o *NestedSubnetPrefix) GetPrefix() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Prefix
}

// GetPrefixOk returns a tuple with the Prefix field value
// and a boolean to check if the value has been set.
func (o *NestedSubnetPrefix) GetPrefixOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Prefix, true
}

// SetPrefix sets field value
func (o *NestedSubnetPrefix) SetPrefix(v string) {
	o.Prefix = v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *NestedSubnetPrefix) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NestedSubnetPrefix) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *NestedSubnetPrefix) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *NestedSubnetPrefix) SetLabel(v string) {
	o.Label = &v
}

// GetIsSecondary returns the IsSecondary field value if set, zero value otherwise.
func (o *NestedSubnetPrefix) GetIsSecondary() bool {
	if o == nil || IsNil(o.IsSecondary) {
		var ret bool
		return ret
	}
	return *o.IsSecondary
}

// GetIsSecondaryOk returns a tuple with the IsSecondary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NestedSubnetPrefix) GetIsSecondaryOk() (*bool, bool) {
	if o == nil || IsNil(o.IsSecondary) {
		return nil, false
	}
	return o.IsSecondary, true
}

// HasIsSecondary returns a boolean if a field has been set.
func (o *NestedSubnetPrefix) HasIsSecondary() bool {
	if o != nil && !IsNil(o.IsSecondary) {
		return true
	}

	return false
}

// SetIsSecondary gets a reference to the given bool and assigns it to the IsSecondary field.
func (o *NestedSubnetPrefix) SetIsSecondary(v bool) {
	o.IsSecondary = &v
}

// GetAutoReserveIps returns the AutoReserveIps field value if set, zero value otherwise.
func (o *NestedSubnetPrefix) GetAutoReserveIps() bool {
	if o == nil || IsNil(o.AutoReserveIps) {
		var ret bool
		return ret
	}
	return *o.AutoReserveIps
}

// GetAutoReserveIpsOk returns a tuple with the AutoReserveIps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NestedSubnetPrefix) GetAutoReserveIpsOk() (*bool, bool) {
	if o == nil || IsNil(o.AutoReserveIps) {
		return nil, false
	}
	return o.AutoReserveIps, true
}

// HasAutoReserveIps returns a boolean if a field has been set.
func (o *NestedSubnetPrefix) HasAutoReserveIps() bool {
	if o != nil && !IsNil(o.AutoReserveIps) {
		return true
	}

	return false
}

// SetAutoReserveIps gets a reference to the given bool and assigns it to the AutoReserveIps field.
func (o *NestedSubnetPrefix) SetAutoReserveIps(v bool) {
	o.AutoReserveIps = &v
}

// GetMarkUtilized returns the MarkUtilized field value if set, zero value otherwise.
func (o *NestedSubnetPrefix) GetMarkUtilized() bool {
	if o == nil || IsNil(o.MarkUtilized) {
		var ret bool
		return ret
	}
	return *o.MarkUtilized
}

// GetMarkUtilizedOk returns a tuple with the MarkUtilized field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NestedSubnetPrefix) GetMarkUtilizedOk() (*bool, bool) {
	if o == nil || IsNil(o.MarkUtilized) {
		return nil, false
	}
	return o.MarkUtilized, true
}

// HasMarkUtilized returns a boolean if a field has been set.
func (o *NestedSubnetPrefix) HasMarkUtilized() bool {
	if o != nil && !IsNil(o.MarkUtilized) {
		return true
	}

	return false
}

// SetMarkUtilized gets a reference to the given bool and assigns it to the MarkUtilized field.
func (o *NestedSubnetPrefix) SetMarkUtilized(v bool) {
	o.MarkUtilized = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *NestedSubnetPrefix) GetStatus() NestedSubnetPrefixStatus {
	if o == nil || IsNil(o.Status) {
		var ret NestedSubnetPrefixStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NestedSubnetPrefix) GetStatusOk() (*NestedSubnetPrefixStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *NestedSubnetPrefix) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given NestedSubnetPrefixStatus and assigns it to the Status field.
func (o *NestedSubnetPrefix) SetStatus(v NestedSubnetPrefixStatus) {
	o.Status = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *NestedSubnetPrefix) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NestedSubnetPrefix) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *NestedSubnetPrefix) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *NestedSubnetPrefix) SetDescription(v string) {
	o.Description = &v
}

// GetComments returns the Comments field value if set, zero value otherwise.
func (o *NestedSubnetPrefix) GetComments() string {
	if o == nil || IsNil(o.Comments) {
		var ret string
		return ret
	}
	return *o.Comments
}

// GetCommentsOk returns a tuple with the Comments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NestedSubnetPrefix) GetCommentsOk() (*string, bool) {
	if o == nil || IsNil(o.Comments) {
		return nil, false
	}
	return o.Comments, true
}

// HasComments returns a boolean if a field has been set.
func (o *NestedSubnetPrefix) HasComments() bool {
	if o != nil && !IsNil(o.Comments) {
		return true
	}

	return false
}

// SetComments gets a reference to the given string and assigns it to the Comments field.
func (o *NestedSubnetPrefix) SetComments(v string) {
	o.Comments = &v
}

func (o NestedSubnetPrefix) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NestedSubnetPrefix) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["url"] = o.Url
	toSerialize["display"] = o.Display
	toSerialize["prefix"] = o.Prefix
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.IsSecondary) {
		toSerialize["is_secondary"] = o.IsSecondary
	}
	if !IsNil(o.AutoReserveIps) {
		toSerialize["auto_reserve_ips"] = o.AutoReserveIps
	}
	if !IsNil(o.MarkUtilized) {
		toSerialize["mark_utilized"] = o.MarkUtilized
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Comments) {
		toSerialize["comments"] = o.Comments
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NestedSubnetPrefix) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"url",
		"display",
		"prefix",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varNestedSubnetPrefix := _NestedSubnetPrefix{}

	err = json.Unmarshal(data, &varNestedSubnetPrefix)

	if err != nil {
		return err
	}

	*o = NestedSubnetPrefix(varNestedSubnetPrefix)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "url")
		delete(additionalProperties, "display")
		delete(additionalProperties, "prefix")
		delete(additionalProperties, "label")
		delete(additionalProperties, "is_secondary")
		delete(additionalProperties, "auto_reserve_ips")
		delete(additionalProperties, "mark_utilized")
		delete(additionalProperties, "status")
		delete(additionalProperties, "description")
		delete(additionalProperties, "comments")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNestedSubnetPrefix struct {
	value *NestedSubnetPrefix
	isSet bool
}

func (v NullableNestedSubnetPrefix) Get() *NestedSubnetPrefix {
	return v.value
}

func (v *NullableNestedSubnetPrefix) Set(val *NestedSubnetPrefix) {
	v.value = val
	v.isSet = true
}

func (v NullableNestedSubnetPrefix) IsSet() bool {
	return v.isSet
}

func (v *NullableNestedSubnetPrefix) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNestedSubnetPrefix(val *NestedSubnetPrefix) *NullableNestedSubnetPrefix {
	return &NullableNestedSubnetPrefix{value: val, isSet: true}
}

func (v NullableNestedSubnetPrefix) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNestedSubnetPrefix) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
