/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.2-Docker-4.0.0 (4.5)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// PatchedSubnetIPAddressRequestRole * `dns` - dns/dns * `data-poi/esgw` - data-poi/esgw * `data-slice/pgwu` - data-slice/pgwu * `sig-poi/dra` - sig-poi/dra * `sig-poi/stp` - sig-poi/stp * `voice-poi/rtpengine` - voice-poi/rtpengine * `voice-poi/sbc` - voice-poi/sbc * `smpp` - smpp/smpp * `gcp/network` - gcp/network * `gcp/gateway` - gcp/gateway * `gcp/reserved` - gcp/future * `gcp/broadcast` - gcp/broadcast
type PatchedSubnetIPAddressRequestRole string

// List of PatchedSubnetIPAddressRequest_role
const (
	PATCHEDSUBNETIPADDRESSREQUESTROLE_DNS                 PatchedSubnetIPAddressRequestRole = "dns"
	PATCHEDSUBNETIPADDRESSREQUESTROLE_DATA_POI_ESGW       PatchedSubnetIPAddressRequestRole = "data-poi/esgw"
	PATCHEDSUBNETIPADDRESSREQUESTROLE_DATA_SLICE_PGWU     PatchedSubnetIPAddressRequestRole = "data-slice/pgwu"
	PATCHEDSUBNETIPADDRESSREQUESTROLE_SIG_POI_DRA         PatchedSubnetIPAddressRequestRole = "sig-poi/dra"
	PATCHEDSUBNETIPADDRESSREQUESTROLE_SIG_POI_STP         PatchedSubnetIPAddressRequestRole = "sig-poi/stp"
	PATCHEDSUBNETIPADDRESSREQUESTROLE_VOICE_POI_RTPENGINE PatchedSubnetIPAddressRequestRole = "voice-poi/rtpengine"
	PATCHEDSUBNETIPADDRESSREQUESTROLE_VOICE_POI_SBC       PatchedSubnetIPAddressRequestRole = "voice-poi/sbc"
	PATCHEDSUBNETIPADDRESSREQUESTROLE_SMPP                PatchedSubnetIPAddressRequestRole = "smpp"
	PATCHEDSUBNETIPADDRESSREQUESTROLE_GCP_NETWORK         PatchedSubnetIPAddressRequestRole = "gcp/network"
	PATCHEDSUBNETIPADDRESSREQUESTROLE_GCP_GATEWAY         PatchedSubnetIPAddressRequestRole = "gcp/gateway"
	PATCHEDSUBNETIPADDRESSREQUESTROLE_GCP_RESERVED        PatchedSubnetIPAddressRequestRole = "gcp/reserved"
	PATCHEDSUBNETIPADDRESSREQUESTROLE_GCP_BROADCAST       PatchedSubnetIPAddressRequestRole = "gcp/broadcast"
	PATCHEDSUBNETIPADDRESSREQUESTROLE_EMPTY               PatchedSubnetIPAddressRequestRole = ""
)

// All allowed values of PatchedSubnetIPAddressRequestRole enum
var AllowedPatchedSubnetIPAddressRequestRoleEnumValues = []PatchedSubnetIPAddressRequestRole{
	"dns",
	"data-poi/esgw",
	"data-slice/pgwu",
	"sig-poi/dra",
	"sig-poi/stp",
	"voice-poi/rtpengine",
	"voice-poi/sbc",
	"smpp",
	"gcp/network",
	"gcp/gateway",
	"gcp/reserved",
	"gcp/broadcast",
	"",
}

func (v *PatchedSubnetIPAddressRequestRole) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PatchedSubnetIPAddressRequestRole(value)
	for _, existing := range AllowedPatchedSubnetIPAddressRequestRoleEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PatchedSubnetIPAddressRequestRole", value)
}

// NewPatchedSubnetIPAddressRequestRoleFromValue returns a pointer to a valid PatchedSubnetIPAddressRequestRole
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPatchedSubnetIPAddressRequestRoleFromValue(v string) (*PatchedSubnetIPAddressRequestRole, error) {
	ev := PatchedSubnetIPAddressRequestRole(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PatchedSubnetIPAddressRequestRole: valid values are %v", v, AllowedPatchedSubnetIPAddressRequestRoleEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PatchedSubnetIPAddressRequestRole) IsValid() bool {
	for _, existing := range AllowedPatchedSubnetIPAddressRequestRoleEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PatchedSubnetIPAddressRequest_role value
func (v PatchedSubnetIPAddressRequestRole) Ptr() *PatchedSubnetIPAddressRequestRole {
	return &v
}

type NullablePatchedSubnetIPAddressRequestRole struct {
	value *PatchedSubnetIPAddressRequestRole
	isSet bool
}

func (v NullablePatchedSubnetIPAddressRequestRole) Get() *PatchedSubnetIPAddressRequestRole {
	return v.value
}

func (v *NullablePatchedSubnetIPAddressRequestRole) Set(val *PatchedSubnetIPAddressRequestRole) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedSubnetIPAddressRequestRole) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedSubnetIPAddressRequestRole) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedSubnetIPAddressRequestRole(val *PatchedSubnetIPAddressRequestRole) *NullablePatchedSubnetIPAddressRequestRole {
	return &NullablePatchedSubnetIPAddressRequestRole{value: val, isSet: true}
}

func (v NullablePatchedSubnetIPAddressRequestRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedSubnetIPAddressRequestRole) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
