/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.2-Docker-4.0.0 (4.5)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
)

// checks if the SubnetRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubnetRequest{}

// SubnetRequest Adds support for custom fields and tags.
type SubnetRequest struct {
	// Name of the Subnet
	Name                 *string                                     `json:"name,omitempty" validate:"regexp=^[a-z0-9_-]+$"`
	Prefixes             []WritableNestedSubnetPrefixRequest         `json:"prefixes,omitempty"`
	Vpc                  NullablePatchedSubnetRequestVpc             `json:"vpc,omitempty"`
	Region               NullablePatchedSubnetRequestRegion          `json:"region,omitempty"`
	Tenant               NullablePatchedSubnetIPAddressRequestTenant `json:"tenant,omitempty"`
	Purpose              NullablePatchedSubnetRequestPurpose         `json:"purpose,omitempty"`
	Description          *string                                     `json:"description,omitempty"`
	Comments             *string                                     `json:"comments,omitempty"`
	CustomFields         map[string]interface{}                      `json:"custom_fields,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SubnetRequest SubnetRequest

// NewSubnetRequest instantiates a new SubnetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubnetRequest() *SubnetRequest {
	this := SubnetRequest{}
	return &this
}

// NewSubnetRequestWithDefaults instantiates a new SubnetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubnetRequestWithDefaults() *SubnetRequest {
	this := SubnetRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SubnetRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubnetRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SubnetRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SubnetRequest) SetName(v string) {
	o.Name = &v
}

// GetPrefixes returns the Prefixes field value if set, zero value otherwise.
func (o *SubnetRequest) GetPrefixes() []WritableNestedSubnetPrefixRequest {
	if o == nil || IsNil(o.Prefixes) {
		var ret []WritableNestedSubnetPrefixRequest
		return ret
	}
	return o.Prefixes
}

// GetPrefixesOk returns a tuple with the Prefixes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubnetRequest) GetPrefixesOk() ([]WritableNestedSubnetPrefixRequest, bool) {
	if o == nil || IsNil(o.Prefixes) {
		return nil, false
	}
	return o.Prefixes, true
}

// HasPrefixes returns a boolean if a field has been set.
func (o *SubnetRequest) HasPrefixes() bool {
	if o != nil && !IsNil(o.Prefixes) {
		return true
	}

	return false
}

// SetPrefixes gets a reference to the given []WritableNestedSubnetPrefixRequest and assigns it to the Prefixes field.
func (o *SubnetRequest) SetPrefixes(v []WritableNestedSubnetPrefixRequest) {
	o.Prefixes = v
}

// GetVpc returns the Vpc field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SubnetRequest) GetVpc() PatchedSubnetRequestVpc {
	if o == nil || IsNil(o.Vpc.Get()) {
		var ret PatchedSubnetRequestVpc
		return ret
	}
	return *o.Vpc.Get()
}

// GetVpcOk returns a tuple with the Vpc field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SubnetRequest) GetVpcOk() (*PatchedSubnetRequestVpc, bool) {
	if o == nil {
		return nil, false
	}
	return o.Vpc.Get(), o.Vpc.IsSet()
}

// HasVpc returns a boolean if a field has been set.
func (o *SubnetRequest) HasVpc() bool {
	if o != nil && o.Vpc.IsSet() {
		return true
	}

	return false
}

// SetVpc gets a reference to the given NullablePatchedSubnetRequestVpc and assigns it to the Vpc field.
func (o *SubnetRequest) SetVpc(v PatchedSubnetRequestVpc) {
	o.Vpc.Set(&v)
}

// SetVpcNil sets the value for Vpc to be an explicit nil
func (o *SubnetRequest) SetVpcNil() {
	o.Vpc.Set(nil)
}

// UnsetVpc ensures that no value is present for Vpc, not even an explicit nil
func (o *SubnetRequest) UnsetVpc() {
	o.Vpc.Unset()
}

// GetRegion returns the Region field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SubnetRequest) GetRegion() PatchedSubnetRequestRegion {
	if o == nil || IsNil(o.Region.Get()) {
		var ret PatchedSubnetRequestRegion
		return ret
	}
	return *o.Region.Get()
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SubnetRequest) GetRegionOk() (*PatchedSubnetRequestRegion, bool) {
	if o == nil {
		return nil, false
	}
	return o.Region.Get(), o.Region.IsSet()
}

// HasRegion returns a boolean if a field has been set.
func (o *SubnetRequest) HasRegion() bool {
	if o != nil && o.Region.IsSet() {
		return true
	}

	return false
}

// SetRegion gets a reference to the given NullablePatchedSubnetRequestRegion and assigns it to the Region field.
func (o *SubnetRequest) SetRegion(v PatchedSubnetRequestRegion) {
	o.Region.Set(&v)
}

// SetRegionNil sets the value for Region to be an explicit nil
func (o *SubnetRequest) SetRegionNil() {
	o.Region.Set(nil)
}

// UnsetRegion ensures that no value is present for Region, not even an explicit nil
func (o *SubnetRequest) UnsetRegion() {
	o.Region.Unset()
}

// GetTenant returns the Tenant field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SubnetRequest) GetTenant() PatchedSubnetIPAddressRequestTenant {
	if o == nil || IsNil(o.Tenant.Get()) {
		var ret PatchedSubnetIPAddressRequestTenant
		return ret
	}
	return *o.Tenant.Get()
}

// GetTenantOk returns a tuple with the Tenant field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SubnetRequest) GetTenantOk() (*PatchedSubnetIPAddressRequestTenant, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tenant.Get(), o.Tenant.IsSet()
}

// HasTenant returns a boolean if a field has been set.
func (o *SubnetRequest) HasTenant() bool {
	if o != nil && o.Tenant.IsSet() {
		return true
	}

	return false
}

// SetTenant gets a reference to the given NullablePatchedSubnetIPAddressRequestTenant and assigns it to the Tenant field.
func (o *SubnetRequest) SetTenant(v PatchedSubnetIPAddressRequestTenant) {
	o.Tenant.Set(&v)
}

// SetTenantNil sets the value for Tenant to be an explicit nil
func (o *SubnetRequest) SetTenantNil() {
	o.Tenant.Set(nil)
}

// UnsetTenant ensures that no value is present for Tenant, not even an explicit nil
func (o *SubnetRequest) UnsetTenant() {
	o.Tenant.Unset()
}

// GetPurpose returns the Purpose field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SubnetRequest) GetPurpose() PatchedSubnetRequestPurpose {
	if o == nil || IsNil(o.Purpose.Get()) {
		var ret PatchedSubnetRequestPurpose
		return ret
	}
	return *o.Purpose.Get()
}

// GetPurposeOk returns a tuple with the Purpose field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SubnetRequest) GetPurposeOk() (*PatchedSubnetRequestPurpose, bool) {
	if o == nil {
		return nil, false
	}
	return o.Purpose.Get(), o.Purpose.IsSet()
}

// HasPurpose returns a boolean if a field has been set.
func (o *SubnetRequest) HasPurpose() bool {
	if o != nil && o.Purpose.IsSet() {
		return true
	}

	return false
}

// SetPurpose gets a reference to the given NullablePatchedSubnetRequestPurpose and assigns it to the Purpose field.
func (o *SubnetRequest) SetPurpose(v PatchedSubnetRequestPurpose) {
	o.Purpose.Set(&v)
}

// SetPurposeNil sets the value for Purpose to be an explicit nil
func (o *SubnetRequest) SetPurposeNil() {
	o.Purpose.Set(nil)
}

// UnsetPurpose ensures that no value is present for Purpose, not even an explicit nil
func (o *SubnetRequest) UnsetPurpose() {
	o.Purpose.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *SubnetRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubnetRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *SubnetRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *SubnetRequest) SetDescription(v string) {
	o.Description = &v
}

// GetComments returns the Comments field value if set, zero value otherwise.
func (o *SubnetRequest) GetComments() string {
	if o == nil || IsNil(o.Comments) {
		var ret string
		return ret
	}
	return *o.Comments
}

// GetCommentsOk returns a tuple with the Comments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubnetRequest) GetCommentsOk() (*string, bool) {
	if o == nil || IsNil(o.Comments) {
		return nil, false
	}
	return o.Comments, true
}

// HasComments returns a boolean if a field has been set.
func (o *SubnetRequest) HasComments() bool {
	if o != nil && !IsNil(o.Comments) {
		return true
	}

	return false
}

// SetComments gets a reference to the given string and assigns it to the Comments field.
func (o *SubnetRequest) SetComments(v string) {
	o.Comments = &v
}

// GetCustomFields returns the CustomFields field value if set, zero value otherwise.
func (o *SubnetRequest) GetCustomFields() map[string]interface{} {
	if o == nil || IsNil(o.CustomFields) {
		var ret map[string]interface{}
		return ret
	}
	return o.CustomFields
}

// GetCustomFieldsOk returns a tuple with the CustomFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubnetRequest) GetCustomFieldsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CustomFields) {
		return map[string]interface{}{}, false
	}
	return o.CustomFields, true
}

// HasCustomFields returns a boolean if a field has been set.
func (o *SubnetRequest) HasCustomFields() bool {
	if o != nil && !IsNil(o.CustomFields) {
		return true
	}

	return false
}

// SetCustomFields gets a reference to the given map[string]interface{} and assigns it to the CustomFields field.
func (o *SubnetRequest) SetCustomFields(v map[string]interface{}) {
	o.CustomFields = v
}

func (o SubnetRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubnetRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Prefixes) {
		toSerialize["prefixes"] = o.Prefixes
	}
	if o.Vpc.IsSet() {
		toSerialize["vpc"] = o.Vpc.Get()
	}
	if o.Region.IsSet() {
		toSerialize["region"] = o.Region.Get()
	}
	if o.Tenant.IsSet() {
		toSerialize["tenant"] = o.Tenant.Get()
	}
	if o.Purpose.IsSet() {
		toSerialize["purpose"] = o.Purpose.Get()
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Comments) {
		toSerialize["comments"] = o.Comments
	}
	if !IsNil(o.CustomFields) {
		toSerialize["custom_fields"] = o.CustomFields
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SubnetRequest) UnmarshalJSON(data []byte) (err error) {
	varSubnetRequest := _SubnetRequest{}

	err = json.Unmarshal(data, &varSubnetRequest)

	if err != nil {
		return err
	}

	*o = SubnetRequest(varSubnetRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "prefixes")
		delete(additionalProperties, "vpc")
		delete(additionalProperties, "region")
		delete(additionalProperties, "tenant")
		delete(additionalProperties, "purpose")
		delete(additionalProperties, "description")
		delete(additionalProperties, "comments")
		delete(additionalProperties, "custom_fields")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSubnetRequest struct {
	value *SubnetRequest
	isSet bool
}

func (v NullableSubnetRequest) Get() *SubnetRequest {
	return v.value
}

func (v *NullableSubnetRequest) Set(val *SubnetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSubnetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSubnetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubnetRequest(val *SubnetRequest) *NullableSubnetRequest {
	return &NullableSubnetRequest{value: val, isSet: true}
}

func (v NullableSubnetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubnetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
