/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.2-Docker-4.0.0 (4.5)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// checks if the NestedSubnetIPAddressRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NestedSubnetIPAddressRequest{}

// NestedSubnetIPAddressRequest Adds support for custom fields and tags.
type NestedSubnetIPAddressRequest struct {
	// IPv4 or IPv6 address (with mask)
	Address              string `json:"address"`
	AdditionalProperties map[string]interface{}
}

type _NestedSubnetIPAddressRequest NestedSubnetIPAddressRequest

// NewNestedSubnetIPAddressRequest instantiates a new NestedSubnetIPAddressRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNestedSubnetIPAddressRequest(address string) *NestedSubnetIPAddressRequest {
	this := NestedSubnetIPAddressRequest{}
	this.Address = address
	return &this
}

// NewNestedSubnetIPAddressRequestWithDefaults instantiates a new NestedSubnetIPAddressRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNestedSubnetIPAddressRequestWithDefaults() *NestedSubnetIPAddressRequest {
	this := NestedSubnetIPAddressRequest{}
	return &this
}

// GetAddress returns the Address field value
func (o *NestedSubnetIPAddressRequest) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *NestedSubnetIPAddressRequest) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *NestedSubnetIPAddressRequest) SetAddress(v string) {
	o.Address = v
}

func (o NestedSubnetIPAddressRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NestedSubnetIPAddressRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NestedSubnetIPAddressRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varNestedSubnetIPAddressRequest := _NestedSubnetIPAddressRequest{}

	err = json.Unmarshal(data, &varNestedSubnetIPAddressRequest)

	if err != nil {
		return err
	}

	*o = NestedSubnetIPAddressRequest(varNestedSubnetIPAddressRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "address")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNestedSubnetIPAddressRequest struct {
	value *NestedSubnetIPAddressRequest
	isSet bool
}

func (v NullableNestedSubnetIPAddressRequest) Get() *NestedSubnetIPAddressRequest {
	return v.value
}

func (v *NullableNestedSubnetIPAddressRequest) Set(val *NestedSubnetIPAddressRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableNestedSubnetIPAddressRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableNestedSubnetIPAddressRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNestedSubnetIPAddressRequest(val *NestedSubnetIPAddressRequest) *NullableNestedSubnetIPAddressRequest {
	return &NullableNestedSubnetIPAddressRequest{value: val, isSet: true}
}

func (v NullableNestedSubnetIPAddressRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNestedSubnetIPAddressRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
