/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.2-Docker-4.0.0 (4.5)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// checks if the BriefNestedVPC type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BriefNestedVPC{}

// BriefNestedVPC Nested VPC representation (read-only).
type BriefNestedVPC struct {
	Id      int32  `json:"id"`
	Url     string `json:"url"`
	Display string `json:"display"`
	// Name of the VPC
	Name                 string        `json:"name" validate:"regexp=^[a-z0-9_-]+$"`
	Environment          NullableInt32 `json:"environment,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BriefNestedVPC BriefNestedVPC

// NewBriefNestedVPC instantiates a new BriefNestedVPC object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBriefNestedVPC(id int32, url string, display string, name string) *BriefNestedVPC {
	this := BriefNestedVPC{}
	this.Id = id
	this.Url = url
	this.Display = display
	this.Name = name
	return &this
}

// NewBriefNestedVPCWithDefaults instantiates a new BriefNestedVPC object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBriefNestedVPCWithDefaults() *BriefNestedVPC {
	this := BriefNestedVPC{}
	return &this
}

// GetId returns the Id field value
func (o *BriefNestedVPC) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BriefNestedVPC) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BriefNestedVPC) SetId(v int32) {
	o.Id = v
}

// GetUrl returns the Url field value
func (o *BriefNestedVPC) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *BriefNestedVPC) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *BriefNestedVPC) SetUrl(v string) {
	o.Url = v
}

// GetDisplay returns the Display field value
func (o *BriefNestedVPC) GetDisplay() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Display
}

// GetDisplayOk returns a tuple with the Display field value
// and a boolean to check if the value has been set.
func (o *BriefNestedVPC) GetDisplayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Display, true
}

// SetDisplay sets field value
func (o *BriefNestedVPC) SetDisplay(v string) {
	o.Display = v
}

// GetName returns the Name field value
func (o *BriefNestedVPC) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *BriefNestedVPC) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *BriefNestedVPC) SetName(v string) {
	o.Name = v
}

// GetEnvironment returns the Environment field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BriefNestedVPC) GetEnvironment() int32 {
	if o == nil || IsNil(o.Environment.Get()) {
		var ret int32
		return ret
	}
	return *o.Environment.Get()
}

// GetEnvironmentOk returns a tuple with the Environment field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BriefNestedVPC) GetEnvironmentOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Environment.Get(), o.Environment.IsSet()
}

// HasEnvironment returns a boolean if a field has been set.
func (o *BriefNestedVPC) HasEnvironment() bool {
	if o != nil && o.Environment.IsSet() {
		return true
	}

	return false
}

// SetEnvironment gets a reference to the given NullableInt32 and assigns it to the Environment field.
func (o *BriefNestedVPC) SetEnvironment(v int32) {
	o.Environment.Set(&v)
}

// SetEnvironmentNil sets the value for Environment to be an explicit nil
func (o *BriefNestedVPC) SetEnvironmentNil() {
	o.Environment.Set(nil)
}

// UnsetEnvironment ensures that no value is present for Environment, not even an explicit nil
func (o *BriefNestedVPC) UnsetEnvironment() {
	o.Environment.Unset()
}

func (o BriefNestedVPC) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BriefNestedVPC) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["url"] = o.Url
	toSerialize["display"] = o.Display
	toSerialize["name"] = o.Name
	if o.Environment.IsSet() {
		toSerialize["environment"] = o.Environment.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BriefNestedVPC) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"url",
		"display",
		"name",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varBriefNestedVPC := _BriefNestedVPC{}

	err = json.Unmarshal(data, &varBriefNestedVPC)

	if err != nil {
		return err
	}

	*o = BriefNestedVPC(varBriefNestedVPC)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "url")
		delete(additionalProperties, "display")
		delete(additionalProperties, "name")
		delete(additionalProperties, "environment")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBriefNestedVPC struct {
	value *BriefNestedVPC
	isSet bool
}

func (v NullableBriefNestedVPC) Get() *BriefNestedVPC {
	return v.value
}

func (v *NullableBriefNestedVPC) Set(val *BriefNestedVPC) {
	v.value = val
	v.isSet = true
}

func (v NullableBriefNestedVPC) IsSet() bool {
	return v.isSet
}

func (v *NullableBriefNestedVPC) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBriefNestedVPC(val *BriefNestedVPC) *NullableBriefNestedVPC {
	return &NullableBriefNestedVPC{value: val, isSet: true}
}

func (v NullableBriefNestedVPC) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBriefNestedVPC) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
