/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.2-Docker-4.0.0 (4.5)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// checks if the WritableNestedSubnetPrefixRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WritableNestedSubnetPrefixRequest{}

// WritableNestedSubnetPrefixRequest struct for WritableNestedSubnetPrefixRequest
type WritableNestedSubnetPrefixRequest struct {
	Id     NullableInt32 `json:"id,omitempty"`
	Prefix string        `json:"prefix"`
	// Name of the Subnet
	Label *string `json:"label,omitempty" validate:"regexp=^[a-z0-9_-]+$"`
	// Set Prefix subnet as secondary
	IsSecondary *bool `json:"is_secondary,omitempty"`
	// Automatically reserve first IPs (network, gateway, etc.)
	AutoReserveFirstIps *bool `json:"auto_reserve_first_ips,omitempty"`
	// Automatically reserve last IPs (broadcast, etc.)
	AutoReserveLastIps *bool `json:"auto_reserve_last_ips,omitempty"`
	// Treat this prefix as fully utilized
	MarkUtilized         *bool                          `json:"mark_utilized,omitempty"`
	Status               *NestedSubnetPrefixStatusValue `json:"status,omitempty"`
	Description          *string                        `json:"description,omitempty"`
	Comments             *string                        `json:"comments,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _WritableNestedSubnetPrefixRequest WritableNestedSubnetPrefixRequest

// NewWritableNestedSubnetPrefixRequest instantiates a new WritableNestedSubnetPrefixRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWritableNestedSubnetPrefixRequest(prefix string) *WritableNestedSubnetPrefixRequest {
	this := WritableNestedSubnetPrefixRequest{}
	this.Prefix = prefix
	var autoReserveFirstIps bool = true
	this.AutoReserveFirstIps = &autoReserveFirstIps
	var autoReserveLastIps bool = true
	this.AutoReserveLastIps = &autoReserveLastIps
	return &this
}

// NewWritableNestedSubnetPrefixRequestWithDefaults instantiates a new WritableNestedSubnetPrefixRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWritableNestedSubnetPrefixRequestWithDefaults() *WritableNestedSubnetPrefixRequest {
	this := WritableNestedSubnetPrefixRequest{}
	var autoReserveFirstIps bool = true
	this.AutoReserveFirstIps = &autoReserveFirstIps
	var autoReserveLastIps bool = true
	this.AutoReserveLastIps = &autoReserveLastIps
	return &this
}

// GetId returns the Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WritableNestedSubnetPrefixRequest) GetId() int32 {
	if o == nil || IsNil(o.Id.Get()) {
		var ret int32
		return ret
	}
	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WritableNestedSubnetPrefixRequest) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// HasId returns a boolean if a field has been set.
func (o *WritableNestedSubnetPrefixRequest) HasId() bool {
	if o != nil && o.Id.IsSet() {
		return true
	}

	return false
}

// SetId gets a reference to the given NullableInt32 and assigns it to the Id field.
func (o *WritableNestedSubnetPrefixRequest) SetId(v int32) {
	o.Id.Set(&v)
}

// SetIdNil sets the value for Id to be an explicit nil
func (o *WritableNestedSubnetPrefixRequest) SetIdNil() {
	o.Id.Set(nil)
}

// UnsetId ensures that no value is present for Id, not even an explicit nil
func (o *WritableNestedSubnetPrefixRequest) UnsetId() {
	o.Id.Unset()
}

// GetPrefix returns the Prefix field value
func (o *WritableNestedSubnetPrefixRequest) GetPrefix() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Prefix
}

// GetPrefixOk returns a tuple with the Prefix field value
// and a boolean to check if the value has been set.
func (o *WritableNestedSubnetPrefixRequest) GetPrefixOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Prefix, true
}

// SetPrefix sets field value
func (o *WritableNestedSubnetPrefixRequest) SetPrefix(v string) {
	o.Prefix = v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *WritableNestedSubnetPrefixRequest) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WritableNestedSubnetPrefixRequest) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *WritableNestedSubnetPrefixRequest) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *WritableNestedSubnetPrefixRequest) SetLabel(v string) {
	o.Label = &v
}

// GetIsSecondary returns the IsSecondary field value if set, zero value otherwise.
func (o *WritableNestedSubnetPrefixRequest) GetIsSecondary() bool {
	if o == nil || IsNil(o.IsSecondary) {
		var ret bool
		return ret
	}
	return *o.IsSecondary
}

// GetIsSecondaryOk returns a tuple with the IsSecondary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WritableNestedSubnetPrefixRequest) GetIsSecondaryOk() (*bool, bool) {
	if o == nil || IsNil(o.IsSecondary) {
		return nil, false
	}
	return o.IsSecondary, true
}

// HasIsSecondary returns a boolean if a field has been set.
func (o *WritableNestedSubnetPrefixRequest) HasIsSecondary() bool {
	if o != nil && !IsNil(o.IsSecondary) {
		return true
	}

	return false
}

// SetIsSecondary gets a reference to the given bool and assigns it to the IsSecondary field.
func (o *WritableNestedSubnetPrefixRequest) SetIsSecondary(v bool) {
	o.IsSecondary = &v
}

// GetAutoReserveFirstIps returns the AutoReserveFirstIps field value if set, zero value otherwise.
func (o *WritableNestedSubnetPrefixRequest) GetAutoReserveFirstIps() bool {
	if o == nil || IsNil(o.AutoReserveFirstIps) {
		var ret bool
		return ret
	}
	return *o.AutoReserveFirstIps
}

// GetAutoReserveFirstIpsOk returns a tuple with the AutoReserveFirstIps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WritableNestedSubnetPrefixRequest) GetAutoReserveFirstIpsOk() (*bool, bool) {
	if o == nil || IsNil(o.AutoReserveFirstIps) {
		return nil, false
	}
	return o.AutoReserveFirstIps, true
}

// HasAutoReserveFirstIps returns a boolean if a field has been set.
func (o *WritableNestedSubnetPrefixRequest) HasAutoReserveFirstIps() bool {
	if o != nil && !IsNil(o.AutoReserveFirstIps) {
		return true
	}

	return false
}

// SetAutoReserveFirstIps gets a reference to the given bool and assigns it to the AutoReserveFirstIps field.
func (o *WritableNestedSubnetPrefixRequest) SetAutoReserveFirstIps(v bool) {
	o.AutoReserveFirstIps = &v
}

// GetAutoReserveLastIps returns the AutoReserveLastIps field value if set, zero value otherwise.
func (o *WritableNestedSubnetPrefixRequest) GetAutoReserveLastIps() bool {
	if o == nil || IsNil(o.AutoReserveLastIps) {
		var ret bool
		return ret
	}
	return *o.AutoReserveLastIps
}

// GetAutoReserveLastIpsOk returns a tuple with the AutoReserveLastIps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WritableNestedSubnetPrefixRequest) GetAutoReserveLastIpsOk() (*bool, bool) {
	if o == nil || IsNil(o.AutoReserveLastIps) {
		return nil, false
	}
	return o.AutoReserveLastIps, true
}

// HasAutoReserveLastIps returns a boolean if a field has been set.
func (o *WritableNestedSubnetPrefixRequest) HasAutoReserveLastIps() bool {
	if o != nil && !IsNil(o.AutoReserveLastIps) {
		return true
	}

	return false
}

// SetAutoReserveLastIps gets a reference to the given bool and assigns it to the AutoReserveLastIps field.
func (o *WritableNestedSubnetPrefixRequest) SetAutoReserveLastIps(v bool) {
	o.AutoReserveLastIps = &v
}

// GetMarkUtilized returns the MarkUtilized field value if set, zero value otherwise.
func (o *WritableNestedSubnetPrefixRequest) GetMarkUtilized() bool {
	if o == nil || IsNil(o.MarkUtilized) {
		var ret bool
		return ret
	}
	return *o.MarkUtilized
}

// GetMarkUtilizedOk returns a tuple with the MarkUtilized field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WritableNestedSubnetPrefixRequest) GetMarkUtilizedOk() (*bool, bool) {
	if o == nil || IsNil(o.MarkUtilized) {
		return nil, false
	}
	return o.MarkUtilized, true
}

// HasMarkUtilized returns a boolean if a field has been set.
func (o *WritableNestedSubnetPrefixRequest) HasMarkUtilized() bool {
	if o != nil && !IsNil(o.MarkUtilized) {
		return true
	}

	return false
}

// SetMarkUtilized gets a reference to the given bool and assigns it to the MarkUtilized field.
func (o *WritableNestedSubnetPrefixRequest) SetMarkUtilized(v bool) {
	o.MarkUtilized = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *WritableNestedSubnetPrefixRequest) GetStatus() NestedSubnetPrefixStatusValue {
	if o == nil || IsNil(o.Status) {
		var ret NestedSubnetPrefixStatusValue
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WritableNestedSubnetPrefixRequest) GetStatusOk() (*NestedSubnetPrefixStatusValue, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *WritableNestedSubnetPrefixRequest) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given NestedSubnetPrefixStatusValue and assigns it to the Status field.
func (o *WritableNestedSubnetPrefixRequest) SetStatus(v NestedSubnetPrefixStatusValue) {
	o.Status = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *WritableNestedSubnetPrefixRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WritableNestedSubnetPrefixRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *WritableNestedSubnetPrefixRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *WritableNestedSubnetPrefixRequest) SetDescription(v string) {
	o.Description = &v
}

// GetComments returns the Comments field value if set, zero value otherwise.
func (o *WritableNestedSubnetPrefixRequest) GetComments() string {
	if o == nil || IsNil(o.Comments) {
		var ret string
		return ret
	}
	return *o.Comments
}

// GetCommentsOk returns a tuple with the Comments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WritableNestedSubnetPrefixRequest) GetCommentsOk() (*string, bool) {
	if o == nil || IsNil(o.Comments) {
		return nil, false
	}
	return o.Comments, true
}

// HasComments returns a boolean if a field has been set.
func (o *WritableNestedSubnetPrefixRequest) HasComments() bool {
	if o != nil && !IsNil(o.Comments) {
		return true
	}

	return false
}

// SetComments gets a reference to the given string and assigns it to the Comments field.
func (o *WritableNestedSubnetPrefixRequest) SetComments(v string) {
	o.Comments = &v
}

func (o WritableNestedSubnetPrefixRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WritableNestedSubnetPrefixRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Id.IsSet() {
		toSerialize["id"] = o.Id.Get()
	}
	toSerialize["prefix"] = o.Prefix
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.IsSecondary) {
		toSerialize["is_secondary"] = o.IsSecondary
	}
	if !IsNil(o.AutoReserveFirstIps) {
		toSerialize["auto_reserve_first_ips"] = o.AutoReserveFirstIps
	}
	if !IsNil(o.AutoReserveLastIps) {
		toSerialize["auto_reserve_last_ips"] = o.AutoReserveLastIps
	}
	if !IsNil(o.MarkUtilized) {
		toSerialize["mark_utilized"] = o.MarkUtilized
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Comments) {
		toSerialize["comments"] = o.Comments
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WritableNestedSubnetPrefixRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"prefix",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varWritableNestedSubnetPrefixRequest := _WritableNestedSubnetPrefixRequest{}

	err = json.Unmarshal(data, &varWritableNestedSubnetPrefixRequest)

	if err != nil {
		return err
	}

	*o = WritableNestedSubnetPrefixRequest(varWritableNestedSubnetPrefixRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "prefix")
		delete(additionalProperties, "label")
		delete(additionalProperties, "is_secondary")
		delete(additionalProperties, "auto_reserve_first_ips")
		delete(additionalProperties, "auto_reserve_last_ips")
		delete(additionalProperties, "mark_utilized")
		delete(additionalProperties, "status")
		delete(additionalProperties, "description")
		delete(additionalProperties, "comments")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWritableNestedSubnetPrefixRequest struct {
	value *WritableNestedSubnetPrefixRequest
	isSet bool
}

func (v NullableWritableNestedSubnetPrefixRequest) Get() *WritableNestedSubnetPrefixRequest {
	return v.value
}

func (v *NullableWritableNestedSubnetPrefixRequest) Set(val *WritableNestedSubnetPrefixRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableWritableNestedSubnetPrefixRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableWritableNestedSubnetPrefixRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWritableNestedSubnetPrefixRequest(val *WritableNestedSubnetPrefixRequest) *NullableWritableNestedSubnetPrefixRequest {
	return &NullableWritableNestedSubnetPrefixRequest{value: val, isSet: true}
}

func (v NullableWritableNestedSubnetPrefixRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWritableNestedSubnetPrefixRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
