/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.1-Docker-3.4.2 (4.5)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// PatchedSubnetRequestPurpose - struct for PatchedSubnetRequestPurpose
type PatchedSubnetRequestPurpose struct {
	BriefSubnetPurposeRequest *BriefSubnetPurposeRequest
	Int32                     *int32
}

// BriefSubnetPurposeRequestAsPatchedSubnetRequestPurpose is a convenience function that returns BriefSubnetPurposeRequest wrapped in PatchedSubnetRequestPurpose
func BriefSubnetPurposeRequestAsPatchedSubnetRequestPurpose(v *BriefSubnetPurposeRequest) PatchedSubnetRequestPurpose {
	return PatchedSubnetRequestPurpose{
		BriefSubnetPurposeRequest: v,
	}
}

// int32AsPatchedSubnetRequestPurpose is a convenience function that returns int32 wrapped in PatchedSubnetRequestPurpose
func Int32AsPatchedSubnetRequestPurpose(v *int32) PatchedSubnetRequestPurpose {
	return PatchedSubnetRequestPurpose{
		Int32: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *PatchedSubnetRequestPurpose) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	match := 0
	// try to unmarshal data into BriefSubnetPurposeRequest
	err = newStrictDecoder(data).Decode(&dst.BriefSubnetPurposeRequest)
	if err == nil {
		jsonBriefSubnetPurposeRequest, _ := json.Marshal(dst.BriefSubnetPurposeRequest)
		if string(jsonBriefSubnetPurposeRequest) == "{}" { // empty struct
			dst.BriefSubnetPurposeRequest = nil
		} else {
			if err = validator.Validate(dst.BriefSubnetPurposeRequest); err != nil {
				dst.BriefSubnetPurposeRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.BriefSubnetPurposeRequest = nil
	}

	// try to unmarshal data into Int32
	err = newStrictDecoder(data).Decode(&dst.Int32)
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			if err = validator.Validate(dst.Int32); err != nil {
				dst.Int32 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Int32 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.BriefSubnetPurposeRequest = nil
		dst.Int32 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PatchedSubnetRequestPurpose)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PatchedSubnetRequestPurpose)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PatchedSubnetRequestPurpose) MarshalJSON() ([]byte, error) {
	if src.BriefSubnetPurposeRequest != nil {
		return json.Marshal(&src.BriefSubnetPurposeRequest)
	}

	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PatchedSubnetRequestPurpose) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.BriefSubnetPurposeRequest != nil {
		return obj.BriefSubnetPurposeRequest
	}

	if obj.Int32 != nil {
		return obj.Int32
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj PatchedSubnetRequestPurpose) GetActualInstanceValue() interface{} {
	if obj.BriefSubnetPurposeRequest != nil {
		return *obj.BriefSubnetPurposeRequest
	}

	if obj.Int32 != nil {
		return *obj.Int32
	}

	// all schemas are nil
	return nil
}

type NullablePatchedSubnetRequestPurpose struct {
	value *PatchedSubnetRequestPurpose
	isSet bool
}

func (v NullablePatchedSubnetRequestPurpose) Get() *PatchedSubnetRequestPurpose {
	return v.value
}

func (v *NullablePatchedSubnetRequestPurpose) Set(val *PatchedSubnetRequestPurpose) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedSubnetRequestPurpose) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedSubnetRequestPurpose) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedSubnetRequestPurpose(val *PatchedSubnetRequestPurpose) *NullablePatchedSubnetRequestPurpose {
	return &NullablePatchedSubnetRequestPurpose{value: val, isSet: true}
}

func (v NullablePatchedSubnetRequestPurpose) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedSubnetRequestPurpose) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
