/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.2-Docker-4.0.0 (4.5)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// NestedSubnetPrefixStatusValue * `container` - Container * `active` - Active * `reserved` - Reserved * `deprecated` - Deprecated
type NestedSubnetPrefixStatusValue string

// List of NestedSubnetPrefix_status_value
const (
	NESTEDSUBNETPREFIXSTATUSVALUE_CONTAINER  NestedSubnetPrefixStatusValue = "container"
	NESTEDSUBNETPREFIXSTATUSVALUE_ACTIVE     NestedSubnetPrefixStatusValue = "active"
	NESTEDSUBNETPREFIXSTATUSVALUE_RESERVED   NestedSubnetPrefixStatusValue = "reserved"
	NESTEDSUBNETPREFIXSTATUSVALUE_DEPRECATED NestedSubnetPrefixStatusValue = "deprecated"
)

// All allowed values of NestedSubnetPrefixStatusValue enum
var AllowedNestedSubnetPrefixStatusValueEnumValues = []NestedSubnetPrefixStatusValue{
	"container",
	"active",
	"reserved",
	"deprecated",
}

func (v *NestedSubnetPrefixStatusValue) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := NestedSubnetPrefixStatusValue(value)
	for _, existing := range AllowedNestedSubnetPrefixStatusValueEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid NestedSubnetPrefixStatusValue", value)
}

// NewNestedSubnetPrefixStatusValueFromValue returns a pointer to a valid NestedSubnetPrefixStatusValue
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewNestedSubnetPrefixStatusValueFromValue(v string) (*NestedSubnetPrefixStatusValue, error) {
	ev := NestedSubnetPrefixStatusValue(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for NestedSubnetPrefixStatusValue: valid values are %v", v, AllowedNestedSubnetPrefixStatusValueEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v NestedSubnetPrefixStatusValue) IsValid() bool {
	for _, existing := range AllowedNestedSubnetPrefixStatusValueEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to NestedSubnetPrefix_status_value value
func (v NestedSubnetPrefixStatusValue) Ptr() *NestedSubnetPrefixStatusValue {
	return &v
}

type NullableNestedSubnetPrefixStatusValue struct {
	value *NestedSubnetPrefixStatusValue
	isSet bool
}

func (v NullableNestedSubnetPrefixStatusValue) Get() *NestedSubnetPrefixStatusValue {
	return v.value
}

func (v *NullableNestedSubnetPrefixStatusValue) Set(val *NestedSubnetPrefixStatusValue) {
	v.value = val
	v.isSet = true
}

func (v NullableNestedSubnetPrefixStatusValue) IsSet() bool {
	return v.isSet
}

func (v *NullableNestedSubnetPrefixStatusValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNestedSubnetPrefixStatusValue(val *NestedSubnetPrefixStatusValue) *NullableNestedSubnetPrefixStatusValue {
	return &NullableNestedSubnetPrefixStatusValue{value: val, isSet: true}
}

func (v NullableNestedSubnetPrefixStatusValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNestedSubnetPrefixStatusValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
