/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.2-Docker-4.0.0 (4.5)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// checks if the BriefNestedVPCRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BriefNestedVPCRequest{}

// BriefNestedVPCRequest Nested VPC representation (read-only).
type BriefNestedVPCRequest struct {
	// Name of the VPC
	Name                 string        `json:"name" validate:"regexp=^[a-z0-9_-]+$"`
	Environment          NullableInt32 `json:"environment,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BriefNestedVPCRequest BriefNestedVPCRequest

// NewBriefNestedVPCRequest instantiates a new BriefNestedVPCRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBriefNestedVPCRequest(name string) *BriefNestedVPCRequest {
	this := BriefNestedVPCRequest{}
	this.Name = name
	return &this
}

// NewBriefNestedVPCRequestWithDefaults instantiates a new BriefNestedVPCRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBriefNestedVPCRequestWithDefaults() *BriefNestedVPCRequest {
	this := BriefNestedVPCRequest{}
	return &this
}

// GetName returns the Name field value
func (o *BriefNestedVPCRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *BriefNestedVPCRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *BriefNestedVPCRequest) SetName(v string) {
	o.Name = v
}

// GetEnvironment returns the Environment field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BriefNestedVPCRequest) GetEnvironment() int32 {
	if o == nil || IsNil(o.Environment.Get()) {
		var ret int32
		return ret
	}
	return *o.Environment.Get()
}

// GetEnvironmentOk returns a tuple with the Environment field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BriefNestedVPCRequest) GetEnvironmentOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Environment.Get(), o.Environment.IsSet()
}

// HasEnvironment returns a boolean if a field has been set.
func (o *BriefNestedVPCRequest) HasEnvironment() bool {
	if o != nil && o.Environment.IsSet() {
		return true
	}

	return false
}

// SetEnvironment gets a reference to the given NullableInt32 and assigns it to the Environment field.
func (o *BriefNestedVPCRequest) SetEnvironment(v int32) {
	o.Environment.Set(&v)
}

// SetEnvironmentNil sets the value for Environment to be an explicit nil
func (o *BriefNestedVPCRequest) SetEnvironmentNil() {
	o.Environment.Set(nil)
}

// UnsetEnvironment ensures that no value is present for Environment, not even an explicit nil
func (o *BriefNestedVPCRequest) UnsetEnvironment() {
	o.Environment.Unset()
}

func (o BriefNestedVPCRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BriefNestedVPCRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if o.Environment.IsSet() {
		toSerialize["environment"] = o.Environment.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BriefNestedVPCRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varBriefNestedVPCRequest := _BriefNestedVPCRequest{}

	err = json.Unmarshal(data, &varBriefNestedVPCRequest)

	if err != nil {
		return err
	}

	*o = BriefNestedVPCRequest(varBriefNestedVPCRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "environment")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBriefNestedVPCRequest struct {
	value *BriefNestedVPCRequest
	isSet bool
}

func (v NullableBriefNestedVPCRequest) Get() *BriefNestedVPCRequest {
	return v.value
}

func (v *NullableBriefNestedVPCRequest) Set(val *BriefNestedVPCRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBriefNestedVPCRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBriefNestedVPCRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBriefNestedVPCRequest(val *BriefNestedVPCRequest) *NullableBriefNestedVPCRequest {
	return &NullableBriefNestedVPCRequest{value: val, isSet: true}
}

func (v NullableBriefNestedVPCRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBriefNestedVPCRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
