/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.1-Docker-3.4.2 (4.5)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// PluginsAirnityIpamSubnetCreateRequest - struct for PluginsAirnityIpamSubnetCreateRequest
type PluginsAirnityIpamSubnetCreateRequest struct {
	SubnetRequest        *SubnetRequest
	ArrayOfSubnetRequest *[]SubnetRequest
}

// SubnetRequestAsPluginsAirnityIpamSubnetCreateRequest is a convenience function that returns SubnetRequest wrapped in PluginsAirnityIpamSubnetCreateRequest
func SubnetRequestAsPluginsAirnityIpamSubnetCreateRequest(v *SubnetRequest) PluginsAirnityIpamSubnetCreateRequest {
	return PluginsAirnityIpamSubnetCreateRequest{
		SubnetRequest: v,
	}
}

// []SubnetRequestAsPluginsAirnityIpamSubnetCreateRequest is a convenience function that returns []SubnetRequest wrapped in PluginsAirnityIpamSubnetCreateRequest
func ArrayOfSubnetRequestAsPluginsAirnityIpamSubnetCreateRequest(v *[]SubnetRequest) PluginsAirnityIpamSubnetCreateRequest {
	return PluginsAirnityIpamSubnetCreateRequest{
		ArrayOfSubnetRequest: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *PluginsAirnityIpamSubnetCreateRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into SubnetRequest
	err = newStrictDecoder(data).Decode(&dst.SubnetRequest)
	if err == nil {
		jsonSubnetRequest, _ := json.Marshal(dst.SubnetRequest)
		if string(jsonSubnetRequest) == "{}" { // empty struct
			dst.SubnetRequest = nil
		} else {
			if err = validator.Validate(dst.SubnetRequest); err != nil {
				dst.SubnetRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.SubnetRequest = nil
	}

	// try to unmarshal data into ArrayOfSubnetRequest
	err = newStrictDecoder(data).Decode(&dst.ArrayOfSubnetRequest)
	if err == nil {
		jsonArrayOfSubnetRequest, _ := json.Marshal(dst.ArrayOfSubnetRequest)
		if string(jsonArrayOfSubnetRequest) == "{}" { // empty struct
			dst.ArrayOfSubnetRequest = nil
		} else {
			if err = validator.Validate(dst.ArrayOfSubnetRequest); err != nil {
				dst.ArrayOfSubnetRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.ArrayOfSubnetRequest = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.SubnetRequest = nil
		dst.ArrayOfSubnetRequest = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PluginsAirnityIpamSubnetCreateRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PluginsAirnityIpamSubnetCreateRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PluginsAirnityIpamSubnetCreateRequest) MarshalJSON() ([]byte, error) {
	if src.SubnetRequest != nil {
		return json.Marshal(&src.SubnetRequest)
	}

	if src.ArrayOfSubnetRequest != nil {
		return json.Marshal(&src.ArrayOfSubnetRequest)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PluginsAirnityIpamSubnetCreateRequest) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.SubnetRequest != nil {
		return obj.SubnetRequest
	}

	if obj.ArrayOfSubnetRequest != nil {
		return obj.ArrayOfSubnetRequest
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj PluginsAirnityIpamSubnetCreateRequest) GetActualInstanceValue() interface{} {
	if obj.SubnetRequest != nil {
		return *obj.SubnetRequest
	}

	if obj.ArrayOfSubnetRequest != nil {
		return *obj.ArrayOfSubnetRequest
	}

	// all schemas are nil
	return nil
}

type NullablePluginsAirnityIpamSubnetCreateRequest struct {
	value *PluginsAirnityIpamSubnetCreateRequest
	isSet bool
}

func (v NullablePluginsAirnityIpamSubnetCreateRequest) Get() *PluginsAirnityIpamSubnetCreateRequest {
	return v.value
}

func (v *NullablePluginsAirnityIpamSubnetCreateRequest) Set(val *PluginsAirnityIpamSubnetCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePluginsAirnityIpamSubnetCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePluginsAirnityIpamSubnetCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePluginsAirnityIpamSubnetCreateRequest(val *PluginsAirnityIpamSubnetCreateRequest) *NullablePluginsAirnityIpamSubnetCreateRequest {
	return &NullablePluginsAirnityIpamSubnetCreateRequest{value: val, isSet: true}
}

func (v NullablePluginsAirnityIpamSubnetCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePluginsAirnityIpamSubnetCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
