/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.2-Docker-4.0.0 (4.5)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
)

// checks if the PatchedWritableSubnetPrefixRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchedWritableSubnetPrefixRequest{}

// PatchedWritableSubnetPrefixRequest Adds support for custom fields and tags.
type PatchedWritableSubnetPrefixRequest struct {
	Prefix *string `json:"prefix,omitempty"`
	// Name of the Subnet
	Label *string `json:"label,omitempty" validate:"regexp=^[a-z0-9_-]+$"`
	// Set Prefix subnet as secondary
	IsSecondary *bool `json:"is_secondary,omitempty"`
	// Automatically reserve first IP addresses (network, gateway, etc.)
	AutoReserveFirstIps *bool `json:"auto_reserve_first_ips,omitempty"`
	// Automatically reserve last IP addresses (broadcast, etc.)
	AutoReserveLastIps *bool `json:"auto_reserve_last_ips,omitempty"`
	// Treat this prefix as fully utilized
	MarkUtilized         *bool                                     `json:"mark_utilized,omitempty"`
	Status               *PatchedWritableSubnetPrefixRequestStatus `json:"status,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PatchedWritableSubnetPrefixRequest PatchedWritableSubnetPrefixRequest

// NewPatchedWritableSubnetPrefixRequest instantiates a new PatchedWritableSubnetPrefixRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchedWritableSubnetPrefixRequest() *PatchedWritableSubnetPrefixRequest {
	this := PatchedWritableSubnetPrefixRequest{}
	return &this
}

// NewPatchedWritableSubnetPrefixRequestWithDefaults instantiates a new PatchedWritableSubnetPrefixRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchedWritableSubnetPrefixRequestWithDefaults() *PatchedWritableSubnetPrefixRequest {
	this := PatchedWritableSubnetPrefixRequest{}
	return &this
}

// GetPrefix returns the Prefix field value if set, zero value otherwise.
func (o *PatchedWritableSubnetPrefixRequest) GetPrefix() string {
	if o == nil || IsNil(o.Prefix) {
		var ret string
		return ret
	}
	return *o.Prefix
}

// GetPrefixOk returns a tuple with the Prefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedWritableSubnetPrefixRequest) GetPrefixOk() (*string, bool) {
	if o == nil || IsNil(o.Prefix) {
		return nil, false
	}
	return o.Prefix, true
}

// HasPrefix returns a boolean if a field has been set.
func (o *PatchedWritableSubnetPrefixRequest) HasPrefix() bool {
	if o != nil && !IsNil(o.Prefix) {
		return true
	}

	return false
}

// SetPrefix gets a reference to the given string and assigns it to the Prefix field.
func (o *PatchedWritableSubnetPrefixRequest) SetPrefix(v string) {
	o.Prefix = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *PatchedWritableSubnetPrefixRequest) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedWritableSubnetPrefixRequest) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *PatchedWritableSubnetPrefixRequest) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *PatchedWritableSubnetPrefixRequest) SetLabel(v string) {
	o.Label = &v
}

// GetIsSecondary returns the IsSecondary field value if set, zero value otherwise.
func (o *PatchedWritableSubnetPrefixRequest) GetIsSecondary() bool {
	if o == nil || IsNil(o.IsSecondary) {
		var ret bool
		return ret
	}
	return *o.IsSecondary
}

// GetIsSecondaryOk returns a tuple with the IsSecondary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedWritableSubnetPrefixRequest) GetIsSecondaryOk() (*bool, bool) {
	if o == nil || IsNil(o.IsSecondary) {
		return nil, false
	}
	return o.IsSecondary, true
}

// HasIsSecondary returns a boolean if a field has been set.
func (o *PatchedWritableSubnetPrefixRequest) HasIsSecondary() bool {
	if o != nil && !IsNil(o.IsSecondary) {
		return true
	}

	return false
}

// SetIsSecondary gets a reference to the given bool and assigns it to the IsSecondary field.
func (o *PatchedWritableSubnetPrefixRequest) SetIsSecondary(v bool) {
	o.IsSecondary = &v
}

// GetAutoReserveFirstIps returns the AutoReserveFirstIps field value if set, zero value otherwise.
func (o *PatchedWritableSubnetPrefixRequest) GetAutoReserveFirstIps() bool {
	if o == nil || IsNil(o.AutoReserveFirstIps) {
		var ret bool
		return ret
	}
	return *o.AutoReserveFirstIps
}

// GetAutoReserveFirstIpsOk returns a tuple with the AutoReserveFirstIps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedWritableSubnetPrefixRequest) GetAutoReserveFirstIpsOk() (*bool, bool) {
	if o == nil || IsNil(o.AutoReserveFirstIps) {
		return nil, false
	}
	return o.AutoReserveFirstIps, true
}

// HasAutoReserveFirstIps returns a boolean if a field has been set.
func (o *PatchedWritableSubnetPrefixRequest) HasAutoReserveFirstIps() bool {
	if o != nil && !IsNil(o.AutoReserveFirstIps) {
		return true
	}

	return false
}

// SetAutoReserveFirstIps gets a reference to the given bool and assigns it to the AutoReserveFirstIps field.
func (o *PatchedWritableSubnetPrefixRequest) SetAutoReserveFirstIps(v bool) {
	o.AutoReserveFirstIps = &v
}

// GetAutoReserveLastIps returns the AutoReserveLastIps field value if set, zero value otherwise.
func (o *PatchedWritableSubnetPrefixRequest) GetAutoReserveLastIps() bool {
	if o == nil || IsNil(o.AutoReserveLastIps) {
		var ret bool
		return ret
	}
	return *o.AutoReserveLastIps
}

// GetAutoReserveLastIpsOk returns a tuple with the AutoReserveLastIps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedWritableSubnetPrefixRequest) GetAutoReserveLastIpsOk() (*bool, bool) {
	if o == nil || IsNil(o.AutoReserveLastIps) {
		return nil, false
	}
	return o.AutoReserveLastIps, true
}

// HasAutoReserveLastIps returns a boolean if a field has been set.
func (o *PatchedWritableSubnetPrefixRequest) HasAutoReserveLastIps() bool {
	if o != nil && !IsNil(o.AutoReserveLastIps) {
		return true
	}

	return false
}

// SetAutoReserveLastIps gets a reference to the given bool and assigns it to the AutoReserveLastIps field.
func (o *PatchedWritableSubnetPrefixRequest) SetAutoReserveLastIps(v bool) {
	o.AutoReserveLastIps = &v
}

// GetMarkUtilized returns the MarkUtilized field value if set, zero value otherwise.
func (o *PatchedWritableSubnetPrefixRequest) GetMarkUtilized() bool {
	if o == nil || IsNil(o.MarkUtilized) {
		var ret bool
		return ret
	}
	return *o.MarkUtilized
}

// GetMarkUtilizedOk returns a tuple with the MarkUtilized field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedWritableSubnetPrefixRequest) GetMarkUtilizedOk() (*bool, bool) {
	if o == nil || IsNil(o.MarkUtilized) {
		return nil, false
	}
	return o.MarkUtilized, true
}

// HasMarkUtilized returns a boolean if a field has been set.
func (o *PatchedWritableSubnetPrefixRequest) HasMarkUtilized() bool {
	if o != nil && !IsNil(o.MarkUtilized) {
		return true
	}

	return false
}

// SetMarkUtilized gets a reference to the given bool and assigns it to the MarkUtilized field.
func (o *PatchedWritableSubnetPrefixRequest) SetMarkUtilized(v bool) {
	o.MarkUtilized = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *PatchedWritableSubnetPrefixRequest) GetStatus() PatchedWritableSubnetPrefixRequestStatus {
	if o == nil || IsNil(o.Status) {
		var ret PatchedWritableSubnetPrefixRequestStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedWritableSubnetPrefixRequest) GetStatusOk() (*PatchedWritableSubnetPrefixRequestStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *PatchedWritableSubnetPrefixRequest) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given PatchedWritableSubnetPrefixRequestStatus and assigns it to the Status field.
func (o *PatchedWritableSubnetPrefixRequest) SetStatus(v PatchedWritableSubnetPrefixRequestStatus) {
	o.Status = &v
}

func (o PatchedWritableSubnetPrefixRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchedWritableSubnetPrefixRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Prefix) {
		toSerialize["prefix"] = o.Prefix
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.IsSecondary) {
		toSerialize["is_secondary"] = o.IsSecondary
	}
	if !IsNil(o.AutoReserveFirstIps) {
		toSerialize["auto_reserve_first_ips"] = o.AutoReserveFirstIps
	}
	if !IsNil(o.AutoReserveLastIps) {
		toSerialize["auto_reserve_last_ips"] = o.AutoReserveLastIps
	}
	if !IsNil(o.MarkUtilized) {
		toSerialize["mark_utilized"] = o.MarkUtilized
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PatchedWritableSubnetPrefixRequest) UnmarshalJSON(data []byte) (err error) {
	varPatchedWritableSubnetPrefixRequest := _PatchedWritableSubnetPrefixRequest{}

	err = json.Unmarshal(data, &varPatchedWritableSubnetPrefixRequest)

	if err != nil {
		return err
	}

	*o = PatchedWritableSubnetPrefixRequest(varPatchedWritableSubnetPrefixRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "prefix")
		delete(additionalProperties, "label")
		delete(additionalProperties, "is_secondary")
		delete(additionalProperties, "auto_reserve_first_ips")
		delete(additionalProperties, "auto_reserve_last_ips")
		delete(additionalProperties, "mark_utilized")
		delete(additionalProperties, "status")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePatchedWritableSubnetPrefixRequest struct {
	value *PatchedWritableSubnetPrefixRequest
	isSet bool
}

func (v NullablePatchedWritableSubnetPrefixRequest) Get() *PatchedWritableSubnetPrefixRequest {
	return v.value
}

func (v *NullablePatchedWritableSubnetPrefixRequest) Set(val *PatchedWritableSubnetPrefixRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedWritableSubnetPrefixRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedWritableSubnetPrefixRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedWritableSubnetPrefixRequest(val *PatchedWritableSubnetPrefixRequest) *NullablePatchedWritableSubnetPrefixRequest {
	return &NullablePatchedWritableSubnetPrefixRequest{value: val, isSet: true}
}

func (v NullablePatchedWritableSubnetPrefixRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedWritableSubnetPrefixRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
