/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.2-Docker-4.0.0 (4.5)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// checks if the VPCRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VPCRequest{}

// VPCRequest Adds support for custom fields and tags.
type VPCRequest struct {
	// Name of the VPC
	Name                 string                             `json:"name" validate:"regexp=^[a-z0-9_-]+$"`
	Environment          NullableBriefVPCRequestEnvironment `json:"environment,omitempty"`
	CustomFieldData      interface{}                        `json:"custom_field_data,omitempty"`
	Tags                 []NestedTagRequest                 `json:"tags,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _VPCRequest VPCRequest

// NewVPCRequest instantiates a new VPCRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVPCRequest(name string) *VPCRequest {
	this := VPCRequest{}
	this.Name = name
	return &this
}

// NewVPCRequestWithDefaults instantiates a new VPCRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVPCRequestWithDefaults() *VPCRequest {
	this := VPCRequest{}
	return &this
}

// GetName returns the Name field value
func (o *VPCRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *VPCRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *VPCRequest) SetName(v string) {
	o.Name = v
}

// GetEnvironment returns the Environment field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VPCRequest) GetEnvironment() BriefVPCRequestEnvironment {
	if o == nil || IsNil(o.Environment.Get()) {
		var ret BriefVPCRequestEnvironment
		return ret
	}
	return *o.Environment.Get()
}

// GetEnvironmentOk returns a tuple with the Environment field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VPCRequest) GetEnvironmentOk() (*BriefVPCRequestEnvironment, bool) {
	if o == nil {
		return nil, false
	}
	return o.Environment.Get(), o.Environment.IsSet()
}

// HasEnvironment returns a boolean if a field has been set.
func (o *VPCRequest) HasEnvironment() bool {
	if o != nil && o.Environment.IsSet() {
		return true
	}

	return false
}

// SetEnvironment gets a reference to the given NullableBriefVPCRequestEnvironment and assigns it to the Environment field.
func (o *VPCRequest) SetEnvironment(v BriefVPCRequestEnvironment) {
	o.Environment.Set(&v)
}

// SetEnvironmentNil sets the value for Environment to be an explicit nil
func (o *VPCRequest) SetEnvironmentNil() {
	o.Environment.Set(nil)
}

// UnsetEnvironment ensures that no value is present for Environment, not even an explicit nil
func (o *VPCRequest) UnsetEnvironment() {
	o.Environment.Unset()
}

// GetCustomFieldData returns the CustomFieldData field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VPCRequest) GetCustomFieldData() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.CustomFieldData
}

// GetCustomFieldDataOk returns a tuple with the CustomFieldData field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VPCRequest) GetCustomFieldDataOk() (*interface{}, bool) {
	if o == nil || IsNil(o.CustomFieldData) {
		return nil, false
	}
	return &o.CustomFieldData, true
}

// HasCustomFieldData returns a boolean if a field has been set.
func (o *VPCRequest) HasCustomFieldData() bool {
	if o != nil && !IsNil(o.CustomFieldData) {
		return true
	}

	return false
}

// SetCustomFieldData gets a reference to the given interface{} and assigns it to the CustomFieldData field.
func (o *VPCRequest) SetCustomFieldData(v interface{}) {
	o.CustomFieldData = v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *VPCRequest) GetTags() []NestedTagRequest {
	if o == nil || IsNil(o.Tags) {
		var ret []NestedTagRequest
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VPCRequest) GetTagsOk() ([]NestedTagRequest, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *VPCRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []NestedTagRequest and assigns it to the Tags field.
func (o *VPCRequest) SetTags(v []NestedTagRequest) {
	o.Tags = v
}

func (o VPCRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VPCRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if o.Environment.IsSet() {
		toSerialize["environment"] = o.Environment.Get()
	}
	if o.CustomFieldData != nil {
		toSerialize["custom_field_data"] = o.CustomFieldData
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *VPCRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varVPCRequest := _VPCRequest{}

	err = json.Unmarshal(data, &varVPCRequest)

	if err != nil {
		return err
	}

	*o = VPCRequest(varVPCRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "environment")
		delete(additionalProperties, "custom_field_data")
		delete(additionalProperties, "tags")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableVPCRequest struct {
	value *VPCRequest
	isSet bool
}

func (v NullableVPCRequest) Get() *VPCRequest {
	return v.value
}

func (v *NullableVPCRequest) Set(val *VPCRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableVPCRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableVPCRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVPCRequest(val *VPCRequest) *NullableVPCRequest {
	return &NullableVPCRequest{value: val, isSet: true}
}

func (v NullableVPCRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVPCRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
