/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.1-Docker-3.4.2 (4.5)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// checks if the AvailablePrefixIP type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AvailablePrefixIP{}

// AvailablePrefixIP Representation of an IP address which does not exist in the database. Used for get_first_available_ip() functionality.  Note: - `address` contains the IP without mask (e.g., \"10.0.1.5\") - `mask_length` is always 32 for IPv4 or 128 for IPv6 (host address) - To get the full CIDR notation, combine: f\"{address}/{mask_length}\"
type AvailablePrefixIP struct {
	Family               int32              `json:"family"`
	Address              string             `json:"address"`
	MaskLength           int32              `json:"mask_length"`
	Vpc                  NullableVPC        `json:"vpc,omitempty"`
	SubnetPrefix         NestedSubnetPrefix `json:"subnet_prefix"`
	Description          *string            `json:"description,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AvailablePrefixIP AvailablePrefixIP

// NewAvailablePrefixIP instantiates a new AvailablePrefixIP object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAvailablePrefixIP(family int32, address string, maskLength int32, subnetPrefix NestedSubnetPrefix) *AvailablePrefixIP {
	this := AvailablePrefixIP{}
	this.Family = family
	this.Address = address
	this.MaskLength = maskLength
	this.SubnetPrefix = subnetPrefix
	return &this
}

// NewAvailablePrefixIPWithDefaults instantiates a new AvailablePrefixIP object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAvailablePrefixIPWithDefaults() *AvailablePrefixIP {
	this := AvailablePrefixIP{}
	return &this
}

// GetFamily returns the Family field value
func (o *AvailablePrefixIP) GetFamily() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Family
}

// GetFamilyOk returns a tuple with the Family field value
// and a boolean to check if the value has been set.
func (o *AvailablePrefixIP) GetFamilyOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Family, true
}

// SetFamily sets field value
func (o *AvailablePrefixIP) SetFamily(v int32) {
	o.Family = v
}

// GetAddress returns the Address field value
func (o *AvailablePrefixIP) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *AvailablePrefixIP) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *AvailablePrefixIP) SetAddress(v string) {
	o.Address = v
}

// GetMaskLength returns the MaskLength field value
func (o *AvailablePrefixIP) GetMaskLength() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaskLength
}

// GetMaskLengthOk returns a tuple with the MaskLength field value
// and a boolean to check if the value has been set.
func (o *AvailablePrefixIP) GetMaskLengthOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaskLength, true
}

// SetMaskLength sets field value
func (o *AvailablePrefixIP) SetMaskLength(v int32) {
	o.MaskLength = v
}

// GetVpc returns the Vpc field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AvailablePrefixIP) GetVpc() VPC {
	if o == nil || IsNil(o.Vpc.Get()) {
		var ret VPC
		return ret
	}
	return *o.Vpc.Get()
}

// GetVpcOk returns a tuple with the Vpc field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AvailablePrefixIP) GetVpcOk() (*VPC, bool) {
	if o == nil {
		return nil, false
	}
	return o.Vpc.Get(), o.Vpc.IsSet()
}

// HasVpc returns a boolean if a field has been set.
func (o *AvailablePrefixIP) HasVpc() bool {
	if o != nil && o.Vpc.IsSet() {
		return true
	}

	return false
}

// SetVpc gets a reference to the given NullableVPC and assigns it to the Vpc field.
func (o *AvailablePrefixIP) SetVpc(v VPC) {
	o.Vpc.Set(&v)
}

// SetVpcNil sets the value for Vpc to be an explicit nil
func (o *AvailablePrefixIP) SetVpcNil() {
	o.Vpc.Set(nil)
}

// UnsetVpc ensures that no value is present for Vpc, not even an explicit nil
func (o *AvailablePrefixIP) UnsetVpc() {
	o.Vpc.Unset()
}

// GetSubnetPrefix returns the SubnetPrefix field value
func (o *AvailablePrefixIP) GetSubnetPrefix() NestedSubnetPrefix {
	if o == nil {
		var ret NestedSubnetPrefix
		return ret
	}

	return o.SubnetPrefix
}

// GetSubnetPrefixOk returns a tuple with the SubnetPrefix field value
// and a boolean to check if the value has been set.
func (o *AvailablePrefixIP) GetSubnetPrefixOk() (*NestedSubnetPrefix, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubnetPrefix, true
}

// SetSubnetPrefix sets field value
func (o *AvailablePrefixIP) SetSubnetPrefix(v NestedSubnetPrefix) {
	o.SubnetPrefix = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *AvailablePrefixIP) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AvailablePrefixIP) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *AvailablePrefixIP) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *AvailablePrefixIP) SetDescription(v string) {
	o.Description = &v
}

func (o AvailablePrefixIP) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AvailablePrefixIP) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["family"] = o.Family
	toSerialize["address"] = o.Address
	toSerialize["mask_length"] = o.MaskLength
	if o.Vpc.IsSet() {
		toSerialize["vpc"] = o.Vpc.Get()
	}
	toSerialize["subnet_prefix"] = o.SubnetPrefix
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AvailablePrefixIP) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"family",
		"address",
		"mask_length",
		"subnet_prefix",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varAvailablePrefixIP := _AvailablePrefixIP{}

	err = json.Unmarshal(data, &varAvailablePrefixIP)

	if err != nil {
		return err
	}

	*o = AvailablePrefixIP(varAvailablePrefixIP)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "family")
		delete(additionalProperties, "address")
		delete(additionalProperties, "mask_length")
		delete(additionalProperties, "vpc")
		delete(additionalProperties, "subnet_prefix")
		delete(additionalProperties, "description")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAvailablePrefixIP struct {
	value *AvailablePrefixIP
	isSet bool
}

func (v NullableAvailablePrefixIP) Get() *AvailablePrefixIP {
	return v.value
}

func (v *NullableAvailablePrefixIP) Set(val *AvailablePrefixIP) {
	v.value = val
	v.isSet = true
}

func (v NullableAvailablePrefixIP) IsSet() bool {
	return v.isSet
}

func (v *NullableAvailablePrefixIP) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAvailablePrefixIP(val *AvailablePrefixIP) *NullableAvailablePrefixIP {
	return &NullableAvailablePrefixIP{value: val, isSet: true}
}

func (v NullableAvailablePrefixIP) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAvailablePrefixIP) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
