/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.2-Docker-4.0.0 (4.5)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// checks if the SubnetPrefixRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubnetPrefixRequest{}

// SubnetPrefixRequest Adds support for custom fields and tags.
type SubnetPrefixRequest struct {
	Prefix string `json:"prefix"`
	// Name of the Subnet
	Label *string `json:"label,omitempty" validate:"regexp=^[a-z0-9_-]+$"`
	// Set Prefix subnet as secondary
	IsSecondary *bool `json:"is_secondary,omitempty"`
	// Automatically reserve first IP addresses (network, gateway, etc.)
	AutoReserveFirstIps *bool `json:"auto_reserve_first_ips,omitempty"`
	// Automatically reserve last IP addresses (broadcast, etc.)
	AutoReserveLastIps *bool `json:"auto_reserve_last_ips,omitempty"`
	// Treat this prefix as fully utilized
	MarkUtilized         *bool                          `json:"mark_utilized,omitempty"`
	Status               *NestedSubnetPrefixStatusValue `json:"status,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SubnetPrefixRequest SubnetPrefixRequest

// NewSubnetPrefixRequest instantiates a new SubnetPrefixRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubnetPrefixRequest(prefix string) *SubnetPrefixRequest {
	this := SubnetPrefixRequest{}
	this.Prefix = prefix
	return &this
}

// NewSubnetPrefixRequestWithDefaults instantiates a new SubnetPrefixRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubnetPrefixRequestWithDefaults() *SubnetPrefixRequest {
	this := SubnetPrefixRequest{}
	return &this
}

// GetPrefix returns the Prefix field value
func (o *SubnetPrefixRequest) GetPrefix() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Prefix
}

// GetPrefixOk returns a tuple with the Prefix field value
// and a boolean to check if the value has been set.
func (o *SubnetPrefixRequest) GetPrefixOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Prefix, true
}

// SetPrefix sets field value
func (o *SubnetPrefixRequest) SetPrefix(v string) {
	o.Prefix = v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *SubnetPrefixRequest) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubnetPrefixRequest) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *SubnetPrefixRequest) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *SubnetPrefixRequest) SetLabel(v string) {
	o.Label = &v
}

// GetIsSecondary returns the IsSecondary field value if set, zero value otherwise.
func (o *SubnetPrefixRequest) GetIsSecondary() bool {
	if o == nil || IsNil(o.IsSecondary) {
		var ret bool
		return ret
	}
	return *o.IsSecondary
}

// GetIsSecondaryOk returns a tuple with the IsSecondary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubnetPrefixRequest) GetIsSecondaryOk() (*bool, bool) {
	if o == nil || IsNil(o.IsSecondary) {
		return nil, false
	}
	return o.IsSecondary, true
}

// HasIsSecondary returns a boolean if a field has been set.
func (o *SubnetPrefixRequest) HasIsSecondary() bool {
	if o != nil && !IsNil(o.IsSecondary) {
		return true
	}

	return false
}

// SetIsSecondary gets a reference to the given bool and assigns it to the IsSecondary field.
func (o *SubnetPrefixRequest) SetIsSecondary(v bool) {
	o.IsSecondary = &v
}

// GetAutoReserveFirstIps returns the AutoReserveFirstIps field value if set, zero value otherwise.
func (o *SubnetPrefixRequest) GetAutoReserveFirstIps() bool {
	if o == nil || IsNil(o.AutoReserveFirstIps) {
		var ret bool
		return ret
	}
	return *o.AutoReserveFirstIps
}

// GetAutoReserveFirstIpsOk returns a tuple with the AutoReserveFirstIps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubnetPrefixRequest) GetAutoReserveFirstIpsOk() (*bool, bool) {
	if o == nil || IsNil(o.AutoReserveFirstIps) {
		return nil, false
	}
	return o.AutoReserveFirstIps, true
}

// HasAutoReserveFirstIps returns a boolean if a field has been set.
func (o *SubnetPrefixRequest) HasAutoReserveFirstIps() bool {
	if o != nil && !IsNil(o.AutoReserveFirstIps) {
		return true
	}

	return false
}

// SetAutoReserveFirstIps gets a reference to the given bool and assigns it to the AutoReserveFirstIps field.
func (o *SubnetPrefixRequest) SetAutoReserveFirstIps(v bool) {
	o.AutoReserveFirstIps = &v
}

// GetAutoReserveLastIps returns the AutoReserveLastIps field value if set, zero value otherwise.
func (o *SubnetPrefixRequest) GetAutoReserveLastIps() bool {
	if o == nil || IsNil(o.AutoReserveLastIps) {
		var ret bool
		return ret
	}
	return *o.AutoReserveLastIps
}

// GetAutoReserveLastIpsOk returns a tuple with the AutoReserveLastIps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubnetPrefixRequest) GetAutoReserveLastIpsOk() (*bool, bool) {
	if o == nil || IsNil(o.AutoReserveLastIps) {
		return nil, false
	}
	return o.AutoReserveLastIps, true
}

// HasAutoReserveLastIps returns a boolean if a field has been set.
func (o *SubnetPrefixRequest) HasAutoReserveLastIps() bool {
	if o != nil && !IsNil(o.AutoReserveLastIps) {
		return true
	}

	return false
}

// SetAutoReserveLastIps gets a reference to the given bool and assigns it to the AutoReserveLastIps field.
func (o *SubnetPrefixRequest) SetAutoReserveLastIps(v bool) {
	o.AutoReserveLastIps = &v
}

// GetMarkUtilized returns the MarkUtilized field value if set, zero value otherwise.
func (o *SubnetPrefixRequest) GetMarkUtilized() bool {
	if o == nil || IsNil(o.MarkUtilized) {
		var ret bool
		return ret
	}
	return *o.MarkUtilized
}

// GetMarkUtilizedOk returns a tuple with the MarkUtilized field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubnetPrefixRequest) GetMarkUtilizedOk() (*bool, bool) {
	if o == nil || IsNil(o.MarkUtilized) {
		return nil, false
	}
	return o.MarkUtilized, true
}

// HasMarkUtilized returns a boolean if a field has been set.
func (o *SubnetPrefixRequest) HasMarkUtilized() bool {
	if o != nil && !IsNil(o.MarkUtilized) {
		return true
	}

	return false
}

// SetMarkUtilized gets a reference to the given bool and assigns it to the MarkUtilized field.
func (o *SubnetPrefixRequest) SetMarkUtilized(v bool) {
	o.MarkUtilized = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *SubnetPrefixRequest) GetStatus() NestedSubnetPrefixStatusValue {
	if o == nil || IsNil(o.Status) {
		var ret NestedSubnetPrefixStatusValue
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubnetPrefixRequest) GetStatusOk() (*NestedSubnetPrefixStatusValue, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *SubnetPrefixRequest) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given NestedSubnetPrefixStatusValue and assigns it to the Status field.
func (o *SubnetPrefixRequest) SetStatus(v NestedSubnetPrefixStatusValue) {
	o.Status = &v
}

func (o SubnetPrefixRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubnetPrefixRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["prefix"] = o.Prefix
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.IsSecondary) {
		toSerialize["is_secondary"] = o.IsSecondary
	}
	if !IsNil(o.AutoReserveFirstIps) {
		toSerialize["auto_reserve_first_ips"] = o.AutoReserveFirstIps
	}
	if !IsNil(o.AutoReserveLastIps) {
		toSerialize["auto_reserve_last_ips"] = o.AutoReserveLastIps
	}
	if !IsNil(o.MarkUtilized) {
		toSerialize["mark_utilized"] = o.MarkUtilized
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SubnetPrefixRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"prefix",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varSubnetPrefixRequest := _SubnetPrefixRequest{}

	err = json.Unmarshal(data, &varSubnetPrefixRequest)

	if err != nil {
		return err
	}

	*o = SubnetPrefixRequest(varSubnetPrefixRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "prefix")
		delete(additionalProperties, "label")
		delete(additionalProperties, "is_secondary")
		delete(additionalProperties, "auto_reserve_first_ips")
		delete(additionalProperties, "auto_reserve_last_ips")
		delete(additionalProperties, "mark_utilized")
		delete(additionalProperties, "status")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSubnetPrefixRequest struct {
	value *SubnetPrefixRequest
	isSet bool
}

func (v NullableSubnetPrefixRequest) Get() *SubnetPrefixRequest {
	return v.value
}

func (v *NullableSubnetPrefixRequest) Set(val *SubnetPrefixRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSubnetPrefixRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSubnetPrefixRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubnetPrefixRequest(val *SubnetPrefixRequest) *NullableSubnetPrefixRequest {
	return &NullableSubnetPrefixRequest{value: val, isSet: true}
}

func (v NullableSubnetPrefixRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubnetPrefixRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
