/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.2-Docker-4.0.0 (4.5)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// checks if the SubnetPrefixForSubnet type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubnetPrefixForSubnet{}

// SubnetPrefixForSubnet Adds support for custom fields and tags.
type SubnetPrefixForSubnet struct {
	Id      int32  `json:"id"`
	Url     string `json:"url"`
	Display string `json:"display"`
	Prefix  string `json:"prefix"`
	// Name of the Subnet
	Label *string `json:"label,omitempty" validate:"regexp=^[a-z0-9_-]+$"`
	// Set Prefix subnet as secondary
	IsSecondary *bool `json:"is_secondary,omitempty"`
	// Automatically reserve first IP addresses (network, gateway, etc.)
	AutoReserveFirstIps *bool `json:"auto_reserve_first_ips,omitempty"`
	// Automatically reserve last IP addresses (broadcast, etc.)
	AutoReserveLastIps   *bool                  `json:"auto_reserve_last_ips,omitempty"`
	Status               map[string]interface{} `json:"status"`
	Description          *string                `json:"description,omitempty"`
	Comments             *string                `json:"comments,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SubnetPrefixForSubnet SubnetPrefixForSubnet

// NewSubnetPrefixForSubnet instantiates a new SubnetPrefixForSubnet object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubnetPrefixForSubnet(id int32, url string, display string, prefix string, status map[string]interface{}) *SubnetPrefixForSubnet {
	this := SubnetPrefixForSubnet{}
	this.Id = id
	this.Url = url
	this.Display = display
	this.Prefix = prefix
	this.Status = status
	return &this
}

// NewSubnetPrefixForSubnetWithDefaults instantiates a new SubnetPrefixForSubnet object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubnetPrefixForSubnetWithDefaults() *SubnetPrefixForSubnet {
	this := SubnetPrefixForSubnet{}
	return &this
}

// GetId returns the Id field value
func (o *SubnetPrefixForSubnet) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SubnetPrefixForSubnet) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SubnetPrefixForSubnet) SetId(v int32) {
	o.Id = v
}

// GetUrl returns the Url field value
func (o *SubnetPrefixForSubnet) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *SubnetPrefixForSubnet) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *SubnetPrefixForSubnet) SetUrl(v string) {
	o.Url = v
}

// GetDisplay returns the Display field value
func (o *SubnetPrefixForSubnet) GetDisplay() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Display
}

// GetDisplayOk returns a tuple with the Display field value
// and a boolean to check if the value has been set.
func (o *SubnetPrefixForSubnet) GetDisplayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Display, true
}

// SetDisplay sets field value
func (o *SubnetPrefixForSubnet) SetDisplay(v string) {
	o.Display = v
}

// GetPrefix returns the Prefix field value
func (o *SubnetPrefixForSubnet) GetPrefix() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Prefix
}

// GetPrefixOk returns a tuple with the Prefix field value
// and a boolean to check if the value has been set.
func (o *SubnetPrefixForSubnet) GetPrefixOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Prefix, true
}

// SetPrefix sets field value
func (o *SubnetPrefixForSubnet) SetPrefix(v string) {
	o.Prefix = v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *SubnetPrefixForSubnet) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubnetPrefixForSubnet) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *SubnetPrefixForSubnet) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *SubnetPrefixForSubnet) SetLabel(v string) {
	o.Label = &v
}

// GetIsSecondary returns the IsSecondary field value if set, zero value otherwise.
func (o *SubnetPrefixForSubnet) GetIsSecondary() bool {
	if o == nil || IsNil(o.IsSecondary) {
		var ret bool
		return ret
	}
	return *o.IsSecondary
}

// GetIsSecondaryOk returns a tuple with the IsSecondary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubnetPrefixForSubnet) GetIsSecondaryOk() (*bool, bool) {
	if o == nil || IsNil(o.IsSecondary) {
		return nil, false
	}
	return o.IsSecondary, true
}

// HasIsSecondary returns a boolean if a field has been set.
func (o *SubnetPrefixForSubnet) HasIsSecondary() bool {
	if o != nil && !IsNil(o.IsSecondary) {
		return true
	}

	return false
}

// SetIsSecondary gets a reference to the given bool and assigns it to the IsSecondary field.
func (o *SubnetPrefixForSubnet) SetIsSecondary(v bool) {
	o.IsSecondary = &v
}

// GetAutoReserveFirstIps returns the AutoReserveFirstIps field value if set, zero value otherwise.
func (o *SubnetPrefixForSubnet) GetAutoReserveFirstIps() bool {
	if o == nil || IsNil(o.AutoReserveFirstIps) {
		var ret bool
		return ret
	}
	return *o.AutoReserveFirstIps
}

// GetAutoReserveFirstIpsOk returns a tuple with the AutoReserveFirstIps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubnetPrefixForSubnet) GetAutoReserveFirstIpsOk() (*bool, bool) {
	if o == nil || IsNil(o.AutoReserveFirstIps) {
		return nil, false
	}
	return o.AutoReserveFirstIps, true
}

// HasAutoReserveFirstIps returns a boolean if a field has been set.
func (o *SubnetPrefixForSubnet) HasAutoReserveFirstIps() bool {
	if o != nil && !IsNil(o.AutoReserveFirstIps) {
		return true
	}

	return false
}

// SetAutoReserveFirstIps gets a reference to the given bool and assigns it to the AutoReserveFirstIps field.
func (o *SubnetPrefixForSubnet) SetAutoReserveFirstIps(v bool) {
	o.AutoReserveFirstIps = &v
}

// GetAutoReserveLastIps returns the AutoReserveLastIps field value if set, zero value otherwise.
func (o *SubnetPrefixForSubnet) GetAutoReserveLastIps() bool {
	if o == nil || IsNil(o.AutoReserveLastIps) {
		var ret bool
		return ret
	}
	return *o.AutoReserveLastIps
}

// GetAutoReserveLastIpsOk returns a tuple with the AutoReserveLastIps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubnetPrefixForSubnet) GetAutoReserveLastIpsOk() (*bool, bool) {
	if o == nil || IsNil(o.AutoReserveLastIps) {
		return nil, false
	}
	return o.AutoReserveLastIps, true
}

// HasAutoReserveLastIps returns a boolean if a field has been set.
func (o *SubnetPrefixForSubnet) HasAutoReserveLastIps() bool {
	if o != nil && !IsNil(o.AutoReserveLastIps) {
		return true
	}

	return false
}

// SetAutoReserveLastIps gets a reference to the given bool and assigns it to the AutoReserveLastIps field.
func (o *SubnetPrefixForSubnet) SetAutoReserveLastIps(v bool) {
	o.AutoReserveLastIps = &v
}

// GetStatus returns the Status field value
func (o *SubnetPrefixForSubnet) GetStatus() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *SubnetPrefixForSubnet) GetStatusOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Status, true
}

// SetStatus sets field value
func (o *SubnetPrefixForSubnet) SetStatus(v map[string]interface{}) {
	o.Status = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *SubnetPrefixForSubnet) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubnetPrefixForSubnet) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *SubnetPrefixForSubnet) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *SubnetPrefixForSubnet) SetDescription(v string) {
	o.Description = &v
}

// GetComments returns the Comments field value if set, zero value otherwise.
func (o *SubnetPrefixForSubnet) GetComments() string {
	if o == nil || IsNil(o.Comments) {
		var ret string
		return ret
	}
	return *o.Comments
}

// GetCommentsOk returns a tuple with the Comments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubnetPrefixForSubnet) GetCommentsOk() (*string, bool) {
	if o == nil || IsNil(o.Comments) {
		return nil, false
	}
	return o.Comments, true
}

// HasComments returns a boolean if a field has been set.
func (o *SubnetPrefixForSubnet) HasComments() bool {
	if o != nil && !IsNil(o.Comments) {
		return true
	}

	return false
}

// SetComments gets a reference to the given string and assigns it to the Comments field.
func (o *SubnetPrefixForSubnet) SetComments(v string) {
	o.Comments = &v
}

func (o SubnetPrefixForSubnet) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubnetPrefixForSubnet) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["url"] = o.Url
	toSerialize["display"] = o.Display
	toSerialize["prefix"] = o.Prefix
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.IsSecondary) {
		toSerialize["is_secondary"] = o.IsSecondary
	}
	if !IsNil(o.AutoReserveFirstIps) {
		toSerialize["auto_reserve_first_ips"] = o.AutoReserveFirstIps
	}
	if !IsNil(o.AutoReserveLastIps) {
		toSerialize["auto_reserve_last_ips"] = o.AutoReserveLastIps
	}
	toSerialize["status"] = o.Status
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Comments) {
		toSerialize["comments"] = o.Comments
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SubnetPrefixForSubnet) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"url",
		"display",
		"prefix",
		"status",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varSubnetPrefixForSubnet := _SubnetPrefixForSubnet{}

	err = json.Unmarshal(data, &varSubnetPrefixForSubnet)

	if err != nil {
		return err
	}

	*o = SubnetPrefixForSubnet(varSubnetPrefixForSubnet)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "url")
		delete(additionalProperties, "display")
		delete(additionalProperties, "prefix")
		delete(additionalProperties, "label")
		delete(additionalProperties, "is_secondary")
		delete(additionalProperties, "auto_reserve_first_ips")
		delete(additionalProperties, "auto_reserve_last_ips")
		delete(additionalProperties, "status")
		delete(additionalProperties, "description")
		delete(additionalProperties, "comments")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSubnetPrefixForSubnet struct {
	value *SubnetPrefixForSubnet
	isSet bool
}

func (v NullableSubnetPrefixForSubnet) Get() *SubnetPrefixForSubnet {
	return v.value
}

func (v *NullableSubnetPrefixForSubnet) Set(val *SubnetPrefixForSubnet) {
	v.value = val
	v.isSet = true
}

func (v NullableSubnetPrefixForSubnet) IsSet() bool {
	return v.isSet
}

func (v *NullableSubnetPrefixForSubnet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubnetPrefixForSubnet(val *SubnetPrefixForSubnet) *NullableSubnetPrefixForSubnet {
	return &NullableSubnetPrefixForSubnet{value: val, isSet: true}
}

func (v NullableSubnetPrefixForSubnet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubnetPrefixForSubnet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
