/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.1-Docker-3.4.2 (4.5)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// PluginsAirnityIpamVpcCreateRequest - struct for PluginsAirnityIpamVpcCreateRequest
type PluginsAirnityIpamVpcCreateRequest struct {
	VPCRequest        *VPCRequest
	ArrayOfVPCRequest *[]VPCRequest
}

// VPCRequestAsPluginsAirnityIpamVpcCreateRequest is a convenience function that returns VPCRequest wrapped in PluginsAirnityIpamVpcCreateRequest
func VPCRequestAsPluginsAirnityIpamVpcCreateRequest(v *VPCRequest) PluginsAirnityIpamVpcCreateRequest {
	return PluginsAirnityIpamVpcCreateRequest{
		VPCRequest: v,
	}
}

// []VPCRequestAsPluginsAirnityIpamVpcCreateRequest is a convenience function that returns []VPCRequest wrapped in PluginsAirnityIpamVpcCreateRequest
func ArrayOfVPCRequestAsPluginsAirnityIpamVpcCreateRequest(v *[]VPCRequest) PluginsAirnityIpamVpcCreateRequest {
	return PluginsAirnityIpamVpcCreateRequest{
		ArrayOfVPCRequest: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *PluginsAirnityIpamVpcCreateRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into VPCRequest
	err = newStrictDecoder(data).Decode(&dst.VPCRequest)
	if err == nil {
		jsonVPCRequest, _ := json.Marshal(dst.VPCRequest)
		if string(jsonVPCRequest) == "{}" { // empty struct
			dst.VPCRequest = nil
		} else {
			if err = validator.Validate(dst.VPCRequest); err != nil {
				dst.VPCRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.VPCRequest = nil
	}

	// try to unmarshal data into ArrayOfVPCRequest
	err = newStrictDecoder(data).Decode(&dst.ArrayOfVPCRequest)
	if err == nil {
		jsonArrayOfVPCRequest, _ := json.Marshal(dst.ArrayOfVPCRequest)
		if string(jsonArrayOfVPCRequest) == "{}" { // empty struct
			dst.ArrayOfVPCRequest = nil
		} else {
			if err = validator.Validate(dst.ArrayOfVPCRequest); err != nil {
				dst.ArrayOfVPCRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.ArrayOfVPCRequest = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.VPCRequest = nil
		dst.ArrayOfVPCRequest = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PluginsAirnityIpamVpcCreateRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PluginsAirnityIpamVpcCreateRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PluginsAirnityIpamVpcCreateRequest) MarshalJSON() ([]byte, error) {
	if src.VPCRequest != nil {
		return json.Marshal(&src.VPCRequest)
	}

	if src.ArrayOfVPCRequest != nil {
		return json.Marshal(&src.ArrayOfVPCRequest)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PluginsAirnityIpamVpcCreateRequest) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.VPCRequest != nil {
		return obj.VPCRequest
	}

	if obj.ArrayOfVPCRequest != nil {
		return obj.ArrayOfVPCRequest
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj PluginsAirnityIpamVpcCreateRequest) GetActualInstanceValue() interface{} {
	if obj.VPCRequest != nil {
		return *obj.VPCRequest
	}

	if obj.ArrayOfVPCRequest != nil {
		return *obj.ArrayOfVPCRequest
	}

	// all schemas are nil
	return nil
}

type NullablePluginsAirnityIpamVpcCreateRequest struct {
	value *PluginsAirnityIpamVpcCreateRequest
	isSet bool
}

func (v NullablePluginsAirnityIpamVpcCreateRequest) Get() *PluginsAirnityIpamVpcCreateRequest {
	return v.value
}

func (v *NullablePluginsAirnityIpamVpcCreateRequest) Set(val *PluginsAirnityIpamVpcCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePluginsAirnityIpamVpcCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePluginsAirnityIpamVpcCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePluginsAirnityIpamVpcCreateRequest(val *PluginsAirnityIpamVpcCreateRequest) *NullablePluginsAirnityIpamVpcCreateRequest {
	return &NullablePluginsAirnityIpamVpcCreateRequest{value: val, isSet: true}
}

func (v NullablePluginsAirnityIpamVpcCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePluginsAirnityIpamVpcCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
