/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.1-Docker-3.4.2 (4.5)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// NestedSubnetPrefixStatusLabel the model 'NestedSubnetPrefixStatusLabel'
type NestedSubnetPrefixStatusLabel string

// List of NestedSubnetPrefix_status_label
const (
	NESTEDSUBNETPREFIXSTATUSLABEL_CONTAINER  NestedSubnetPrefixStatusLabel = "Container"
	NESTEDSUBNETPREFIXSTATUSLABEL_ACTIVE     NestedSubnetPrefixStatusLabel = "Active"
	NESTEDSUBNETPREFIXSTATUSLABEL_RESERVED   NestedSubnetPrefixStatusLabel = "Reserved"
	NESTEDSUBNETPREFIXSTATUSLABEL_DEPRECATED NestedSubnetPrefixStatusLabel = "Deprecated"
)

// All allowed values of NestedSubnetPrefixStatusLabel enum
var AllowedNestedSubnetPrefixStatusLabelEnumValues = []NestedSubnetPrefixStatusLabel{
	"Container",
	"Active",
	"Reserved",
	"Deprecated",
}

func (v *NestedSubnetPrefixStatusLabel) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := NestedSubnetPrefixStatusLabel(value)
	for _, existing := range AllowedNestedSubnetPrefixStatusLabelEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid NestedSubnetPrefixStatusLabel", value)
}

// NewNestedSubnetPrefixStatusLabelFromValue returns a pointer to a valid NestedSubnetPrefixStatusLabel
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewNestedSubnetPrefixStatusLabelFromValue(v string) (*NestedSubnetPrefixStatusLabel, error) {
	ev := NestedSubnetPrefixStatusLabel(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for NestedSubnetPrefixStatusLabel: valid values are %v", v, AllowedNestedSubnetPrefixStatusLabelEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v NestedSubnetPrefixStatusLabel) IsValid() bool {
	for _, existing := range AllowedNestedSubnetPrefixStatusLabelEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to NestedSubnetPrefix_status_label value
func (v NestedSubnetPrefixStatusLabel) Ptr() *NestedSubnetPrefixStatusLabel {
	return &v
}

type NullableNestedSubnetPrefixStatusLabel struct {
	value *NestedSubnetPrefixStatusLabel
	isSet bool
}

func (v NullableNestedSubnetPrefixStatusLabel) Get() *NestedSubnetPrefixStatusLabel {
	return v.value
}

func (v *NullableNestedSubnetPrefixStatusLabel) Set(val *NestedSubnetPrefixStatusLabel) {
	v.value = val
	v.isSet = true
}

func (v NullableNestedSubnetPrefixStatusLabel) IsSet() bool {
	return v.isSet
}

func (v *NullableNestedSubnetPrefixStatusLabel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNestedSubnetPrefixStatusLabel(val *NestedSubnetPrefixStatusLabel) *NullableNestedSubnetPrefixStatusLabel {
	return &NullableNestedSubnetPrefixStatusLabel{value: val, isSet: true}
}

func (v NullableNestedSubnetPrefixStatusLabel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNestedSubnetPrefixStatusLabel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
