/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.1-Docker-3.4.2 (4.5)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// PluginsAirnityIpamSubnetpurposeCreateRequest - struct for PluginsAirnityIpamSubnetpurposeCreateRequest
type PluginsAirnityIpamSubnetpurposeCreateRequest struct {
	SubnetPurposeRequest        *SubnetPurposeRequest
	ArrayOfSubnetPurposeRequest *[]SubnetPurposeRequest
}

// SubnetPurposeRequestAsPluginsAirnityIpamSubnetpurposeCreateRequest is a convenience function that returns SubnetPurposeRequest wrapped in PluginsAirnityIpamSubnetpurposeCreateRequest
func SubnetPurposeRequestAsPluginsAirnityIpamSubnetpurposeCreateRequest(v *SubnetPurposeRequest) PluginsAirnityIpamSubnetpurposeCreateRequest {
	return PluginsAirnityIpamSubnetpurposeCreateRequest{
		SubnetPurposeRequest: v,
	}
}

// []SubnetPurposeRequestAsPluginsAirnityIpamSubnetpurposeCreateRequest is a convenience function that returns []SubnetPurposeRequest wrapped in PluginsAirnityIpamSubnetpurposeCreateRequest
func ArrayOfSubnetPurposeRequestAsPluginsAirnityIpamSubnetpurposeCreateRequest(v *[]SubnetPurposeRequest) PluginsAirnityIpamSubnetpurposeCreateRequest {
	return PluginsAirnityIpamSubnetpurposeCreateRequest{
		ArrayOfSubnetPurposeRequest: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *PluginsAirnityIpamSubnetpurposeCreateRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into SubnetPurposeRequest
	err = newStrictDecoder(data).Decode(&dst.SubnetPurposeRequest)
	if err == nil {
		jsonSubnetPurposeRequest, _ := json.Marshal(dst.SubnetPurposeRequest)
		if string(jsonSubnetPurposeRequest) == "{}" { // empty struct
			dst.SubnetPurposeRequest = nil
		} else {
			if err = validator.Validate(dst.SubnetPurposeRequest); err != nil {
				dst.SubnetPurposeRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.SubnetPurposeRequest = nil
	}

	// try to unmarshal data into ArrayOfSubnetPurposeRequest
	err = newStrictDecoder(data).Decode(&dst.ArrayOfSubnetPurposeRequest)
	if err == nil {
		jsonArrayOfSubnetPurposeRequest, _ := json.Marshal(dst.ArrayOfSubnetPurposeRequest)
		if string(jsonArrayOfSubnetPurposeRequest) == "{}" { // empty struct
			dst.ArrayOfSubnetPurposeRequest = nil
		} else {
			if err = validator.Validate(dst.ArrayOfSubnetPurposeRequest); err != nil {
				dst.ArrayOfSubnetPurposeRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.ArrayOfSubnetPurposeRequest = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.SubnetPurposeRequest = nil
		dst.ArrayOfSubnetPurposeRequest = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PluginsAirnityIpamSubnetpurposeCreateRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PluginsAirnityIpamSubnetpurposeCreateRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PluginsAirnityIpamSubnetpurposeCreateRequest) MarshalJSON() ([]byte, error) {
	if src.SubnetPurposeRequest != nil {
		return json.Marshal(&src.SubnetPurposeRequest)
	}

	if src.ArrayOfSubnetPurposeRequest != nil {
		return json.Marshal(&src.ArrayOfSubnetPurposeRequest)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PluginsAirnityIpamSubnetpurposeCreateRequest) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.SubnetPurposeRequest != nil {
		return obj.SubnetPurposeRequest
	}

	if obj.ArrayOfSubnetPurposeRequest != nil {
		return obj.ArrayOfSubnetPurposeRequest
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj PluginsAirnityIpamSubnetpurposeCreateRequest) GetActualInstanceValue() interface{} {
	if obj.SubnetPurposeRequest != nil {
		return *obj.SubnetPurposeRequest
	}

	if obj.ArrayOfSubnetPurposeRequest != nil {
		return *obj.ArrayOfSubnetPurposeRequest
	}

	// all schemas are nil
	return nil
}

type NullablePluginsAirnityIpamSubnetpurposeCreateRequest struct {
	value *PluginsAirnityIpamSubnetpurposeCreateRequest
	isSet bool
}

func (v NullablePluginsAirnityIpamSubnetpurposeCreateRequest) Get() *PluginsAirnityIpamSubnetpurposeCreateRequest {
	return v.value
}

func (v *NullablePluginsAirnityIpamSubnetpurposeCreateRequest) Set(val *PluginsAirnityIpamSubnetpurposeCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePluginsAirnityIpamSubnetpurposeCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePluginsAirnityIpamSubnetpurposeCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePluginsAirnityIpamSubnetpurposeCreateRequest(val *PluginsAirnityIpamSubnetpurposeCreateRequest) *NullablePluginsAirnityIpamSubnetpurposeCreateRequest {
	return &NullablePluginsAirnityIpamSubnetpurposeCreateRequest{value: val, isSet: true}
}

func (v NullablePluginsAirnityIpamSubnetpurposeCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePluginsAirnityIpamSubnetpurposeCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
