/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.1-Docker-3.4.2 (4.5)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the VPC type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VPC{}

// VPC Adds support for custom fields and tags.
type VPC struct {
	Id      int32       `json:"id"`
	Url     string      `json:"url"`
	Display interface{} `json:"display,omitempty"`
	// Name of the VPC
	Name                 string                   `json:"name" validate:"regexp=^[a-z0-9_-]+$"`
	Environment          NullableBriefEnvironment `json:"environment,omitempty"`
	Created              NullableTime             `json:"created,omitempty"`
	LastUpdated          NullableTime             `json:"last_updated,omitempty"`
	CustomFieldData      interface{}              `json:"custom_field_data,omitempty"`
	Tags                 []NestedTag              `json:"tags,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _VPC VPC

// NewVPC instantiates a new VPC object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVPC(id int32, url string, name string) *VPC {
	this := VPC{}
	this.Id = id
	this.Url = url
	this.Name = name
	return &this
}

// NewVPCWithDefaults instantiates a new VPC object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVPCWithDefaults() *VPC {
	this := VPC{}
	return &this
}

// GetId returns the Id field value
func (o *VPC) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *VPC) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *VPC) SetId(v int32) {
	o.Id = v
}

// GetUrl returns the Url field value
func (o *VPC) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *VPC) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *VPC) SetUrl(v string) {
	o.Url = v
}

// GetDisplay returns the Display field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VPC) GetDisplay() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Display
}

// GetDisplayOk returns a tuple with the Display field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VPC) GetDisplayOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Display) {
		return nil, false
	}
	return &o.Display, true
}

// HasDisplay returns a boolean if a field has been set.
func (o *VPC) HasDisplay() bool {
	if o != nil && !IsNil(o.Display) {
		return true
	}

	return false
}

// SetDisplay gets a reference to the given interface{} and assigns it to the Display field.
func (o *VPC) SetDisplay(v interface{}) {
	o.Display = v
}

// GetName returns the Name field value
func (o *VPC) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *VPC) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *VPC) SetName(v string) {
	o.Name = v
}

// GetEnvironment returns the Environment field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VPC) GetEnvironment() BriefEnvironment {
	if o == nil || IsNil(o.Environment.Get()) {
		var ret BriefEnvironment
		return ret
	}
	return *o.Environment.Get()
}

// GetEnvironmentOk returns a tuple with the Environment field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VPC) GetEnvironmentOk() (*BriefEnvironment, bool) {
	if o == nil {
		return nil, false
	}
	return o.Environment.Get(), o.Environment.IsSet()
}

// HasEnvironment returns a boolean if a field has been set.
func (o *VPC) HasEnvironment() bool {
	if o != nil && o.Environment.IsSet() {
		return true
	}

	return false
}

// SetEnvironment gets a reference to the given NullableBriefEnvironment and assigns it to the Environment field.
func (o *VPC) SetEnvironment(v BriefEnvironment) {
	o.Environment.Set(&v)
}

// SetEnvironmentNil sets the value for Environment to be an explicit nil
func (o *VPC) SetEnvironmentNil() {
	o.Environment.Set(nil)
}

// UnsetEnvironment ensures that no value is present for Environment, not even an explicit nil
func (o *VPC) UnsetEnvironment() {
	o.Environment.Unset()
}

// GetCreated returns the Created field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VPC) GetCreated() time.Time {
	if o == nil || IsNil(o.Created.Get()) {
		var ret time.Time
		return ret
	}
	return *o.Created.Get()
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VPC) GetCreatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.Created.Get(), o.Created.IsSet()
}

// HasCreated returns a boolean if a field has been set.
func (o *VPC) HasCreated() bool {
	if o != nil && o.Created.IsSet() {
		return true
	}

	return false
}

// SetCreated gets a reference to the given NullableTime and assigns it to the Created field.
func (o *VPC) SetCreated(v time.Time) {
	o.Created.Set(&v)
}

// SetCreatedNil sets the value for Created to be an explicit nil
func (o *VPC) SetCreatedNil() {
	o.Created.Set(nil)
}

// UnsetCreated ensures that no value is present for Created, not even an explicit nil
func (o *VPC) UnsetCreated() {
	o.Created.Unset()
}

// GetLastUpdated returns the LastUpdated field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VPC) GetLastUpdated() time.Time {
	if o == nil || IsNil(o.LastUpdated.Get()) {
		var ret time.Time
		return ret
	}
	return *o.LastUpdated.Get()
}

// GetLastUpdatedOk returns a tuple with the LastUpdated field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VPC) GetLastUpdatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastUpdated.Get(), o.LastUpdated.IsSet()
}

// HasLastUpdated returns a boolean if a field has been set.
func (o *VPC) HasLastUpdated() bool {
	if o != nil && o.LastUpdated.IsSet() {
		return true
	}

	return false
}

// SetLastUpdated gets a reference to the given NullableTime and assigns it to the LastUpdated field.
func (o *VPC) SetLastUpdated(v time.Time) {
	o.LastUpdated.Set(&v)
}

// SetLastUpdatedNil sets the value for LastUpdated to be an explicit nil
func (o *VPC) SetLastUpdatedNil() {
	o.LastUpdated.Set(nil)
}

// UnsetLastUpdated ensures that no value is present for LastUpdated, not even an explicit nil
func (o *VPC) UnsetLastUpdated() {
	o.LastUpdated.Unset()
}

// GetCustomFieldData returns the CustomFieldData field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VPC) GetCustomFieldData() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.CustomFieldData
}

// GetCustomFieldDataOk returns a tuple with the CustomFieldData field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VPC) GetCustomFieldDataOk() (*interface{}, bool) {
	if o == nil || IsNil(o.CustomFieldData) {
		return nil, false
	}
	return &o.CustomFieldData, true
}

// HasCustomFieldData returns a boolean if a field has been set.
func (o *VPC) HasCustomFieldData() bool {
	if o != nil && !IsNil(o.CustomFieldData) {
		return true
	}

	return false
}

// SetCustomFieldData gets a reference to the given interface{} and assigns it to the CustomFieldData field.
func (o *VPC) SetCustomFieldData(v interface{}) {
	o.CustomFieldData = v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *VPC) GetTags() []NestedTag {
	if o == nil || IsNil(o.Tags) {
		var ret []NestedTag
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VPC) GetTagsOk() ([]NestedTag, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *VPC) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []NestedTag and assigns it to the Tags field.
func (o *VPC) SetTags(v []NestedTag) {
	o.Tags = v
}

func (o VPC) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VPC) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["url"] = o.Url
	if o.Display != nil {
		toSerialize["display"] = o.Display
	}
	toSerialize["name"] = o.Name
	if o.Environment.IsSet() {
		toSerialize["environment"] = o.Environment.Get()
	}
	if o.Created.IsSet() {
		toSerialize["created"] = o.Created.Get()
	}
	if o.LastUpdated.IsSet() {
		toSerialize["last_updated"] = o.LastUpdated.Get()
	}
	if o.CustomFieldData != nil {
		toSerialize["custom_field_data"] = o.CustomFieldData
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *VPC) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"url",
		"name",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varVPC := _VPC{}

	err = json.Unmarshal(data, &varVPC)

	if err != nil {
		return err
	}

	*o = VPC(varVPC)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "url")
		delete(additionalProperties, "display")
		delete(additionalProperties, "name")
		delete(additionalProperties, "environment")
		delete(additionalProperties, "created")
		delete(additionalProperties, "last_updated")
		delete(additionalProperties, "custom_field_data")
		delete(additionalProperties, "tags")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableVPC struct {
	value *VPC
	isSet bool
}

func (v NullableVPC) Get() *VPC {
	return v.value
}

func (v *NullableVPC) Set(val *VPC) {
	v.value = val
	v.isSet = true
}

func (v NullableVPC) IsSet() bool {
	return v.isSet
}

func (v *NullableVPC) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVPC(val *VPC) *NullableVPC {
	return &NullableVPC{value: val, isSet: true}
}

func (v NullableVPC) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVPC) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
