/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.1-Docker-3.4.2 (4.5)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// PatchedSubnetIPAddressRequestStatus * `active` - Active * `reserved` - Reserved * `deprecated` - Deprecated * `dhcp` - DHCP * `slaac` - SLAAC * `auto` - Auto
type PatchedSubnetIPAddressRequestStatus string

// List of PatchedSubnetIPAddressRequest_status
const (
	PATCHEDSUBNETIPADDRESSREQUESTSTATUS_ACTIVE     PatchedSubnetIPAddressRequestStatus = "active"
	PATCHEDSUBNETIPADDRESSREQUESTSTATUS_RESERVED   PatchedSubnetIPAddressRequestStatus = "reserved"
	PATCHEDSUBNETIPADDRESSREQUESTSTATUS_DEPRECATED PatchedSubnetIPAddressRequestStatus = "deprecated"
	PATCHEDSUBNETIPADDRESSREQUESTSTATUS_DHCP       PatchedSubnetIPAddressRequestStatus = "dhcp"
	PATCHEDSUBNETIPADDRESSREQUESTSTATUS_SLAAC      PatchedSubnetIPAddressRequestStatus = "slaac"
	PATCHEDSUBNETIPADDRESSREQUESTSTATUS_AUTO       PatchedSubnetIPAddressRequestStatus = "auto"
)

// All allowed values of PatchedSubnetIPAddressRequestStatus enum
var AllowedPatchedSubnetIPAddressRequestStatusEnumValues = []PatchedSubnetIPAddressRequestStatus{
	"active",
	"reserved",
	"deprecated",
	"dhcp",
	"slaac",
	"auto",
}

func (v *PatchedSubnetIPAddressRequestStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PatchedSubnetIPAddressRequestStatus(value)
	for _, existing := range AllowedPatchedSubnetIPAddressRequestStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PatchedSubnetIPAddressRequestStatus", value)
}

// NewPatchedSubnetIPAddressRequestStatusFromValue returns a pointer to a valid PatchedSubnetIPAddressRequestStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPatchedSubnetIPAddressRequestStatusFromValue(v string) (*PatchedSubnetIPAddressRequestStatus, error) {
	ev := PatchedSubnetIPAddressRequestStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PatchedSubnetIPAddressRequestStatus: valid values are %v", v, AllowedPatchedSubnetIPAddressRequestStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PatchedSubnetIPAddressRequestStatus) IsValid() bool {
	for _, existing := range AllowedPatchedSubnetIPAddressRequestStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PatchedSubnetIPAddressRequest_status value
func (v PatchedSubnetIPAddressRequestStatus) Ptr() *PatchedSubnetIPAddressRequestStatus {
	return &v
}

type NullablePatchedSubnetIPAddressRequestStatus struct {
	value *PatchedSubnetIPAddressRequestStatus
	isSet bool
}

func (v NullablePatchedSubnetIPAddressRequestStatus) Get() *PatchedSubnetIPAddressRequestStatus {
	return v.value
}

func (v *NullablePatchedSubnetIPAddressRequestStatus) Set(val *PatchedSubnetIPAddressRequestStatus) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedSubnetIPAddressRequestStatus) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedSubnetIPAddressRequestStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedSubnetIPAddressRequestStatus(val *PatchedSubnetIPAddressRequestStatus) *NullablePatchedSubnetIPAddressRequestStatus {
	return &NullablePatchedSubnetIPAddressRequestStatus{value: val, isSet: true}
}

func (v NullablePatchedSubnetIPAddressRequestStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedSubnetIPAddressRequestStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
