/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.2-Docker-4.0.0 (4.5)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// PatchedSubnetIPAddressRequestVpc - struct for PatchedSubnetIPAddressRequestVpc
type PatchedSubnetIPAddressRequestVpc struct {
	BriefVPCRequest *BriefVPCRequest
	Int32           *int32
}

// BriefVPCRequestAsPatchedSubnetIPAddressRequestVpc is a convenience function that returns BriefVPCRequest wrapped in PatchedSubnetIPAddressRequestVpc
func BriefVPCRequestAsPatchedSubnetIPAddressRequestVpc(v *BriefVPCRequest) PatchedSubnetIPAddressRequestVpc {
	return PatchedSubnetIPAddressRequestVpc{
		BriefVPCRequest: v,
	}
}

// int32AsPatchedSubnetIPAddressRequestVpc is a convenience function that returns int32 wrapped in PatchedSubnetIPAddressRequestVpc
func Int32AsPatchedSubnetIPAddressRequestVpc(v *int32) PatchedSubnetIPAddressRequestVpc {
	return PatchedSubnetIPAddressRequestVpc{
		Int32: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *PatchedSubnetIPAddressRequestVpc) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	match := 0
	// try to unmarshal data into BriefVPCRequest
	err = newStrictDecoder(data).Decode(&dst.BriefVPCRequest)
	if err == nil {
		jsonBriefVPCRequest, _ := json.Marshal(dst.BriefVPCRequest)
		if string(jsonBriefVPCRequest) == "{}" { // empty struct
			dst.BriefVPCRequest = nil
		} else {
			if err = validator.Validate(dst.BriefVPCRequest); err != nil {
				dst.BriefVPCRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.BriefVPCRequest = nil
	}

	// try to unmarshal data into Int32
	err = newStrictDecoder(data).Decode(&dst.Int32)
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			if err = validator.Validate(dst.Int32); err != nil {
				dst.Int32 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Int32 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.BriefVPCRequest = nil
		dst.Int32 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PatchedSubnetIPAddressRequestVpc)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PatchedSubnetIPAddressRequestVpc)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PatchedSubnetIPAddressRequestVpc) MarshalJSON() ([]byte, error) {
	if src.BriefVPCRequest != nil {
		return json.Marshal(&src.BriefVPCRequest)
	}

	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PatchedSubnetIPAddressRequestVpc) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.BriefVPCRequest != nil {
		return obj.BriefVPCRequest
	}

	if obj.Int32 != nil {
		return obj.Int32
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj PatchedSubnetIPAddressRequestVpc) GetActualInstanceValue() interface{} {
	if obj.BriefVPCRequest != nil {
		return *obj.BriefVPCRequest
	}

	if obj.Int32 != nil {
		return *obj.Int32
	}

	// all schemas are nil
	return nil
}

type NullablePatchedSubnetIPAddressRequestVpc struct {
	value *PatchedSubnetIPAddressRequestVpc
	isSet bool
}

func (v NullablePatchedSubnetIPAddressRequestVpc) Get() *PatchedSubnetIPAddressRequestVpc {
	return v.value
}

func (v *NullablePatchedSubnetIPAddressRequestVpc) Set(val *PatchedSubnetIPAddressRequestVpc) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedSubnetIPAddressRequestVpc) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedSubnetIPAddressRequestVpc) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedSubnetIPAddressRequestVpc(val *PatchedSubnetIPAddressRequestVpc) *NullablePatchedSubnetIPAddressRequestVpc {
	return &NullablePatchedSubnetIPAddressRequestVpc{value: val, isSet: true}
}

func (v NullablePatchedSubnetIPAddressRequestVpc) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedSubnetIPAddressRequestVpc) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
